<?php

// MANTICORE-ONLY (Http\Multipart has no php counterpart). No server: bodies are
// built by hand with boundary `----mcb` and fed through a chunk source that
// answers 7 bytes per read, so the delimiter straddles reads; `split` feeds the
// same body one byte per read. The `fields` var_dump in the expected file is
// GENERATED by php: parse_str('a=1&b[x]=2', $r); var_dump($r). Every temp file
// is unlinked at the end; the malformed cases count the temp dir's `php*`
// files before and after, so a false parseAll() provably leaves none behind —
// @serial, so no other case's temp files move that count meanwhile.

function chunked(string $s, int $n): \Closure
{
    $pos = 0;
    return function (int $max) use ($s, $n, &$pos): string {
        $take = $max < $n ? $max : $n;
        $out = substr($s, $pos, $take);
        $pos = $pos + strlen($out);
        return $out;
    };
}

function body(array<int, string> $parts): string
{
    $b = '';
    foreach ($parts as $p) { $b .= "------mcb\r\n" . $p . "\r\n"; }
    return $b . "------mcb--\r\n";
}

function part(string $disp, string $data, string $type = ''): string
{
    $h = 'Content-Disposition: form-data; ' . $disp . "\r\n";
    if ($type !== '') { $h .= 'Content-Type: ' . $type . "\r\n"; }
    return $h . "\r\n" . $data;
}

function vis(string $s): string
{
    return str_replace(["\r", "\n"], ['\r', '\n'], $s);
}

function tmpCount(): int
{
    $g = glob(sys_get_temp_dir() . '/php*');
    return $g === false ? -1 : count($g);
}

function run(string $label, string $body, int $n, int $maxFiles = 20, int $maxSize = 2097152): \Http\Multipart
{
    $m = new \Http\Multipart('multipart/form-data; boundary=----mcb', chunked($body, $n), $maxFiles, $maxSize);
    $ok = $m->parseAll();
    echo "[$label] ok=" . ($ok ? 'true' : 'false') . " files=" . count($m->files()) . "\n";
    foreach ($m->files() as $f) {
        echo "  field=" . $f->field . " name=" . vis($f->name) . " full=" . vis($f->fullPath)
            . " type=" . $f->type . " size=" . $f->size . " error=" . $f->error
            . " valid=" . ($f->isValid() ? 'yes' : 'no');
        if ($f->tmpName === '') {
            echo " tmp=''\n";
        } else {
            $c = file_get_contents($f->tmpName);
            echo " tmp=" . (is_file($f->tmpName) ? 'file' : 'MISSING')
                . " bytes=" . vis($c === false ? '?' : $c)
                . " same=" . ($f->contents() === $c ? 'yes' : 'no') . "\n";
        }
    }
    return $m;
}

$hello = part('name="f"; filename="hello.txt"', 'hello world', 'text/plain');

/** @var array<int, \Http\Multipart> */
$all = [];

$m = run('fields', body([part('name="a"', '1'), part('name="b[x]"', '2')]), 7);
var_dump($m->fields());
$all[] = $m;

$all[] = run('file', body([$hello]), 7);

$m = run('two-in-array', body([
    part('name="f[]"; filename="a.txt"', 'A'),
    part('name="f[]"; filename="b.txt"', 'BB'),
    part('name="g"', 'G'),
]), 7);
echo '  fields: ' . count($m->fields()) . ' f=' . (isset($m->fields()['f']) ? 'set' : 'unset') . "\n";
$all[] = $m;

$all[] = run('path-basename', body([
    part('name="f"; filename="C:\dir\x.txt"', 'x'),
    part('name="g"; filename="/home/u/y.txt"', 'y'),
]), 7);

$all[] = run('quoted', body([
    part('name="f"; filename="a\"b.txt"', 'q'),
    part('name="g"; filename="c%22d.txt"', 'q'),
    part('name="h"; filename="e\\f.txt"', 'q'),
    part('filename="k.txt"; name="k"', 'q'),
]), 7);

$all[] = run('empty-file', body([part('name="f"; filename=""', '')]), 7);

$all[] = run('too-big', body([$hello]), 7, 20, 10);

$all[] = run('max-files', body([
    part('name="a"; filename="a.txt"', 'A'),
    part('name="b"; filename="b.txt"', 'B'),
    part('name="c"; filename="c.txt"', 'C'),
]), 7, 2);

// a later MAX_FILE_SIZE=0 lifts the cap: php's `max_file_size &&` treats 0 as none
$all[] = run('MAX_FILE_SIZE', body([part('name="MAX_FILE_SIZE"', '5'), $hello, part('name="MAX_FILE_SIZE"', '0'), $hello]), 7);

$all[] = run('partial', "------mcb\r\n" . part('name="a"', '1') . "\r\n------mcb\r\n" . substr($hello, 0, strlen($hello) - 3), 7);

$m = run('no-boundary', body([$hello]), 7);
$all[] = $m;
echo '  boundaryOf: "' . \Http\Multipart::boundaryOf('multipart/form-data') . '" "'
    . \Http\Multipart::boundaryOf('multipart/form-data; boundary=----mcb') . '" "'
    . \Http\Multipart::boundaryOf('multipart/form-data; Boundary="x y"; charset=utf-8') . "\"\n";
$nb = new \Http\Multipart('multipart/form-data', chunked(body([$hello]), 7), 20, 2097152);
echo '  parseAll: ' . ($nb->parseAll() ? 'true' : 'false') . "\n";

// malformed: the file parsed before the bad head leaves no temp file behind
$before = tmpCount();
$all[] = run('bad-head', body([$hello, part('name="a"', '1'), 'Content-Disposition: form-data; name="b"' . "\r\n" . '2']), 7);
echo '  orphans: ' . (tmpCount() - $before) . "\n";

$all[] = run('preamble', "junk\r\n--junk\r\n------mc\r\n" . body([part('name="a"', '1'), $hello]), 7);

$all[] = run('crlf-in-body', body([part('name="f"; filename="c.bin"', "x\r\n--not\r\n--\r\n------mcc\r\ny", 'application/octet-stream')]), 7);

$all[] = run('split', body([$hello]), 1);

$all[] = run('empty', "------mcb--\r\n", 7);

// A file already dropped (over max_file_uploads=1) or failed (filename="" → 4)
// that is then cut at EOF keeps its verdict: PARTIAL is only for a file still
// being written.
$all[] = run('partial-dropped', "------mcb\r\n" . part('name="a"; filename="a.txt"', 'A') . "\r\n------mcb\r\n"
    . part('name="b"; filename="b.txt"', 'BBBBBBBBBB'), 7, 1);
$all[] = run('partial-dropped', "------mcb\r\n" . part('name="a"; filename="a.txt"', 'A') . "\r\n------mcb\r\n"
    . part('name="c"; filename=""', 'CCC'), 7);

// Junk after a delimiter is malformed (400), and the good file parsed before it
// leaves no temp file behind. A body cut right after a delimiter is truncation:
// the part before it is complete.
$before = tmpCount();
$m = run('garbage-after-delim', "------mcb\r\n" . $hello . "\r\n------mcbXX\r\n" . part('name="a"', '1') . "\r\n------mcb--\r\n", 7);
$all[] = $m;
echo '  orphans: ' . (tmpCount() - $before) . "\n";
$m = run('garbage-after-delim', "------mcb\r\n" . $hello . "\r\n------mcb", 7);
$all[] = $m;

// rfc1867 registers the part name as sent: no urldecode (php_register_variable
// still folds `.`/space to `_` and nests brackets). A field whose name merely
// contains `filename=` is a text field, not a file part.
$m = run('raw-name', body([
    part('name="a%20b"', '1'),
    part('name="p.q"', '2'),
    part('name="r[x%5D]"', '3'),
    part('name="xfilename=1"', '4'),
]), 7);
var_dump($m->fields());
$all[] = $m;

// php 8.5 (php-cgi oracle): "Mime headers garbled" only when NEITHER name= nor
// filename= is present; a file part with only filename= is registered
// ($_FILES[0]), so here it is kept with field ''. The garbled part is malformed.
$all[] = run('file-no-name', body([$hello, part('filename="x.txt"', 'x')]), 7);
$all[] = run('file-no-name', body([part('name="a"', '1'), part('', 'x')]), 7);

foreach ($all as $m) {
    foreach ($m->files() as $f) {
        if ($f->tmpName !== '') { unlink($f->tmpName); }
    }
}
echo "done\n";
