<?php

// MANTICORE-ONLY (no Http\Server in php): a compat(true) server exercising
// $_FILES, is_uploaded_file()/move_uploaded_file() per request, and the temp
// sweep at request end (Task 6). Bodies are hand-built with boundary `----mcb`
// (the body()/part() helpers of http_multipart.php). Every `var_dump($_FILES)`
// block in the expected file is GENERATED by php: the same bodies posted with
// curl --data-binary to `php -d xdebug.mode=off -S 127.0.0.1:8099 dump.php`
// (dump.php = `var_dump($_FILES)`), with every tmp_name masked to `TMP` by the
// same preg_replace the handler applies here. The handler unlinks NOTHING:
// after each response the client checks the tmp path from the `X-Tmp` header
// is gone (`exists after=no`), and that a moved file survived the sweep.
// `anon` is a file part with filename= but no name= — php (rfc1867) files it
// under `$_FILES[0]`. `throws` reads $_FILES then throws: 500, tmp still swept.

use function Async\async;
use function Async\spawn;

function listen(int $from): array<int, mixed>
{
    for ($p = $from; $p < $from + 60; $p = $p + 1) {
        $s = @stream_socket_server('tcp://127.0.0.1:' . $p);
        if ($s !== false) { stream_set_blocking($s, false); return [$s, $p]; }
    }
    return [false, 0];
}

/** One complete raw response; body length taken from Content-Length. */
function readOne(\Resource $c): string
{
    $buf = '';
    while (true) {
        $end = strpos($buf, "\r\n\r\n");
        if ($end !== false) {
            $len = 0;
            foreach (explode("\r\n", substr($buf, 0, $end)) as $line) {
                if (stripos($line, 'content-length:') === 0) { $len = (int)trim(substr($line, 15)); }
            }
            if (strlen($buf) >= $end + 4 + $len) { return substr($buf, 0, $end + 4 + $len); }
        }
        $chunk = fread($c, 4096);
        if ($chunk === '') { return $buf; }
        $buf .= $chunk;
    }
}

function headerOf(string $raw, string $name): string
{
    $end = strpos($raw, "\r\n\r\n");
    $head = $end === false ? $raw : substr($raw, 0, $end);
    foreach (explode("\r\n", $head) as $line) {
        if (stripos($line, $name . ':') === 0) { return trim(substr($line, strlen($name) + 1)); }
    }
    return '';
}

function part(string $disp, string $data, string $type = ''): string
{
    $h = 'Content-Disposition: form-data; ' . $disp . "\r\n";
    if ($type !== '') { $h .= 'Content-Type: ' . $type . "\r\n"; }
    return $h . "\r\n" . $data;
}

function body(array<int, string> $parts): string
{
    $b = '';
    foreach ($parts as $p) { $b .= "------mcb\r\n" . $p . "\r\n"; }
    return $b . "------mcb--\r\n";
}

function post(string $path, string $b): string
{
    return 'POST ' . $path . " HTTP/1.1\r\nHost: t\r\nContent-Type: multipart/form-data; boundary=----mcb\r\n"
        . 'Content-Length: ' . strlen($b) . "\r\n\r\n" . $b;
}

/** Send one request, print its status line + body, then check the tmp path after the response. */
function roundtrip(string $label, \Resource $c, string $raw): void
{
    fwrite($c, $raw);
    $res = readOne($c);
    $end = strpos($res, "\r\n\r\n");
    $status = $end === false ? $res : substr($res, 0, strpos($res, "\r\n"));
    $body = $end === false ? '' : substr($res, $end + 4);
    $tmp = headerOf($res, 'X-Tmp');
    // The sweep runs in the server's `finally` after the write; give the
    // reactor a turn so a partial write cannot race the check.
    \Async\delay(0.02);
    echo '=== ', $label, ': ', $status, "\n", $body;
    echo 'tmp given=', ($tmp !== '' ? 'yes' : 'no'), ' exists after=', (($tmp !== '' && file_exists($tmp)) ? 'yes' : 'no'), "\n";
}

function filesHandler(\Http\Request $req, string $dest): \Http\Response
{
    ob_start();
    var_dump($_FILES);
    $raw = ob_get_clean();
    $masked = preg_replace('#string\(\d+\) "(/[^"]+)"#', 'string(3) "TMP"', $raw === false ? '' : $raw);
    $dump = $masked === null ? '' : $masked;
    $tmp = '';
    foreach ($req->allFiles() as $f) {
        if ($tmp === '' && $f->tmpName !== '') { $tmp = $f->tmpName; }
    }
    if ($req->path === '/throws') {
        header('X-Tmp: ' . $tmp);
        throw new \RuntimeException('boom');
    }
    $out = $dump;
    if ($req->path === '/move') {
        $t = $_FILES['f']['tmp_name'];
        $out .= 'is_uploaded before=' . var_export(is_uploaded_file($t), true) . "\n";
        $out .= 'stranger=' . var_export(is_uploaded_file($dest), true) . "\n";
        $out .= 'move=' . var_export(move_uploaded_file($t, $dest), true) . "\n";
        $out .= 'is_uploaded after=' . var_export(is_uploaded_file($t), true) . "\n";
        $out .= 'move again=' . var_export(move_uploaded_file($t, $dest . '.2'), true) . "\n";
        $out .= 'dest exists=' . var_export(file_exists($dest), true) . ' dest=' . file_get_contents($dest) . "\n";
    }
    return (new \Http\Response())->text($out)->header('X-Tmp', $tmp);
}

$dest = sys_get_temp_dir() . '/mc_http_files_compat.moved';
@unlink($dest);

[$l, $port] = listen(50300);
if ($l === false) { echo "no free port\n"; return; }

// onError is installed for the /throws case, as in http_multipart.php: the
// default 500 path SIGSEGVs through the real socket pump (pre-existing).
$server = \Http\Server::onListener($l)
    ->serverName('')
    ->acceptWait(0.02)
    ->compat(true)
    ->onError(function (\Throwable $e, ?\Http\Request $req): \Http\Response {
        return (new \Http\Response(500))->text("Internal Server Error\n")->close();
    });

async(function () use ($server, $port, $dest) {
    spawn(function () use ($server, $dest) {
        $server->serve(function (\Http\Request $req) use ($dest): \Http\Response {
            return filesHandler($req, $dest);
        });
    });
    \Async\delay(0.05);

    $c = fsockopen('127.0.0.1', $port);

    // move FIRST: the very first request of the process registers its upload
    // before any request ever began — is_uploaded_file / move_uploaded_file on
    // `f` prove that path; the moved file survives the sweep.
    roundtrip('move', $c, post('/move', body([part('name="a"', '1'),
        part('name="f"; filename="hello.txt"', 'hello world', 'text/plain')])));
    echo 'dest after=', (file_exists($dest) ? 'yes' : 'no'), "\n";
    @unlink($dest);

    // single: one text field + one file under `f`.
    roundtrip('single', $c, post('/upload', body([part('name="a"', '1'),
        part('name="f"; filename="hello.txt"', 'hello world', 'text/plain')])));

    // array: two files under `f[]`; the first has no Content-Type.
    roundtrip('array', $c, post('/upload', body([part('name="f[]"; filename="a.txt"', 'AAA'),
        part('name="f[]"; filename="b.txt"', 'BBBB', 'text/plain')])));

    // nested: a text field and a file under `u[...]`.
    roundtrip('nested', $c, post('/upload', body([part('name="u[name]"', 'Ada'),
        part('name="u[avatar]"; filename="avatar.png"', 'PNGDATA', 'image/png')])));

    // anon: filename= with no name= lands under $_FILES[0], the named one under `g`.
    roundtrip('anon', $c, post('/upload', body([part('filename="anon.txt"', 'ANON', 'text/plain'),
        part('name="g"; filename="g.txt"', 'GG', 'text/plain')])));

    // nobody: a GET seeds an empty $_FILES.
    roundtrip('nobody', $c, "GET /upload HTTP/1.1\r\nHost: t\r\n\r\n");
    fclose($c);

    // throws: the handler reads $_FILES then throws — 500, and the tmp is still swept.
    $c2 = fsockopen('127.0.0.1', $port);
    roundtrip('throws', $c2, post('/throws', body([part('name="f"; filename="d.txt"', 'doomed', 'text/plain')])));
    fclose($c2);

    $server->stop();
    $st = $server->stats();
    echo 'served=', $st['served'], ' errors=', $st['errors'], "\n";
});

echo "done\n";
