<?php

// MANTICORE-ONLY (no Http\Server in php): Request::multipart() over a
// STREAMED body (streamBodies(true), maxBodySize(1024) so a 1 MiB upload is
// handed over as a Reader). The handler pulls the parts one at a time: a
// 1 MiB file part read in 8 KiB pieces + one field; it answers the byte count
// and the md5 of what it read, and the client prints the md5 of what it sent
// — the two must be equal. The file bytes carry `\r\n------mc` fragments (a
// near-delimiter) and every byte value, and the client dribbles the body in
// 16 KiB writes so the delimiter and the fragments straddle reads. No temp
// file is created: TMPDIR points at a private, empty dir for the whole run.
// Then the misuse cases: allFiles() on a streamed multipart body, multipart()
// on a buffered one, multipart() twice — each a LogicException whose message
// the handler prints. The expected output is written BY HAND; the md5 is
// php's `md5()` of the same generated bytes.

use function Async\async;
use function Async\spawn;

final class Client
{
    private string $buf = '';

    public function __construct(private \Resource $c) {}

    public function send(string $raw): void { fwrite($this->c, $raw); }

    /** One complete response; body length taken from Content-Length. */
    public function readOne(): string
    {
        while (true) {
            $end = strpos($this->buf, "\r\n\r\n");
            if ($end !== false) {
                $head = substr($this->buf, 0, $end);
                $len = 0;
                foreach (explode("\r\n", $head) as $line) {
                    if (stripos($line, 'content-length:') === 0) {
                        $len = (int)trim(substr($line, 15));
                    }
                }
                $whole = $end + 4 + $len;
                if (strlen($this->buf) >= $whole) {
                    $out = substr($this->buf, 0, $whole);
                    $this->buf = substr($this->buf, $whole);
                    return $out;
                }
            }
            $chunk = fread($this->c, 4096);
            if ($chunk === '') {
                $out = $this->buf;
                $this->buf = '';
                return $out;
            }
            $this->buf .= $chunk;
        }
    }

    public function close(): void { fclose($this->c); }
}

function show(string $label, string $raw): void
{
    $end = strpos($raw, "\r\n\r\n");
    $head = $end === false ? $raw : substr($raw, 0, $end);
    $body = $end === false ? '' : substr($raw, $end + 4);
    $lines = explode("\r\n", $head);
    echo $label, ': ', $lines[0], ' body=', $body, "\n";
}

function part(string $disp, string $data, string $type = ''): string
{
    $h = 'Content-Disposition: form-data; ' . $disp . "\r\n";
    if ($type !== '') { $h .= 'Content-Type: ' . $type . "\r\n"; }
    return $h . "\r\n" . $data;
}

function body(array<int, string> $parts): string
{
    $b = '';
    foreach ($parts as $p) { $b .= "------mcb\r\n" . $p . "\r\n"; }
    return $b . "------mcb--\r\n";
}

function post(string $path, string $b): string
{
    return 'POST ' . $path . " HTTP/1.1\r\nHost: t\r\nContent-Type: multipart/form-data; boundary=----mcb\r\n"
        . 'Content-Length: ' . strlen($b) . "\r\n\r\n" . $b;
}

/** 1 MiB: every byte value, with a near-delimiter fragment in every 256-byte block. */
function fileBytes(): string
{
    $block = "\r\n------mc";
    for ($i = strlen($block); $i < 256; $i = $i + 1) {
        $block .= chr($i);
    }
    return str_repeat($block, 4096);
}

function streamHandler(\Http\Request $req): \Http\Response
{
    try {
        if ($req->path === '/files') {
            return (new \Http\Response())->text('count=' . count($req->allFiles()));
        }
        if ($req->path === '/post') {
            return (new \Http\Response())->text('post=' . count($req->postArray()));
        }
        $n = 0;
        $bytes = 0;
        $data = '';
        $fields = [];
        foreach ($req->multipart() as $p) {
            $n = $n + 1;
            if ($p->filename === '') {
                $fields[$p->name] = $p->readAll();
                continue;
            }
            while (($c = $p->read(8192)) !== '') {
                $bytes = $bytes + strlen($c);
                $data = $data . $c;
            }
        }
        if ($req->path === '/twice') {
            foreach ($req->multipart() as $p) {
                $n = $n + 1;
            }
        }
        return (new \Http\Response())->text('parts=' . $n . ' bytes=' . $bytes . ' md5=' . md5($data)
            . ' a=' . ($fields['a'] ?? '-'));
    } catch (\LogicException $e) {
        return (new \Http\Response())->text('LogicException: ' . $e->getMessage());
    }
}

$tmpDir = sys_get_temp_dir() . '/mc_mpstream_' . getmypid();
@mkdir($tmpDir);
putenv('TMPDIR=' . $tmpDir);

$port = 0;
$listener = false;
for ($p = 50100; $p < 50180; $p = $p + 1) {
    $s = @stream_socket_server('tcp://127.0.0.1:' . $p);
    if ($s !== false) {
        $listener = $s;
        $port = $p;
        break;
    }
}
if ($listener === false) {
    echo "no free port\n";
    return;
}
stream_set_blocking($listener, false);

$server = \Http\Server::onListener($listener)
    ->serverName('')
    ->acceptWait(0.02)
    ->maxBodySize(1024)
    ->streamBodies(true);

async(function () use ($server, $port, $tmpDir) {
    spawn(function () use ($server) {
        $server->serve(function (\Http\Request $req): \Http\Response {
            return streamHandler($req);
        });
    });

    \Async\delay(0.05);

    $file = fileBytes();
    $big = body([part('name="f"; filename="big.bin"', $file, 'application/octet-stream'), part('name="a"', '1')]);

    // stream: the 1 MiB body dribbled in 16 KiB writes.
    $c = new Client(fsockopen('127.0.0.1', $port));
    $c->send('POST /stream HTTP/1.1' . "\r\nHost: t\r\nContent-Type: multipart/form-data; boundary=----mcb\r\n"
        . 'Content-Length: ' . strlen($big) . "\r\n\r\n");
    $pos = 0;
    $n = strlen($big);
    while ($pos < $n) {
        $chunk = substr($big, $pos, 16384);
        $c->send($chunk);
        $pos = $pos + strlen($chunk);
        usleep(1000);
    }
    show('stream', $c->readOne());
    echo 'expect=', md5($file), "\n";

    // files: allFiles() on a streamed multipart body.
    $c->send(post('/files', $big));
    show('files', $c->readOne());

    // post: postArray() on a streamed multipart body.
    $c->send(post('/post', $big));
    show('post', $c->readOne());

    // twice: the body is consumed by the first multipart().
    $small = body([part('name="f"; filename="s.bin"', str_repeat('x', 2000)), part('name="a"', '1')]);
    $c->send(post('/twice', $small));
    show('twice', $c->readOne());

    // buffered: under maxBodySize the body is buffered, multipart() refuses.
    $tiny = body([part('name="a"', '1')]);
    $c->send(post('/stream', $tiny));
    show('buffered', $c->readOne());
    $c->close();

    $server->stop();
    $st = $server->stats();
    echo 'served=', $st['served'], ' errors=', $st['errors'], "\n";
    $g = glob($tmpDir . '/*');
    echo 'tmp files: ', ($g === false || count($g) === 0) ? 'none' : count($g), "\n";
    @rmdir($tmpDir);
});

echo "done\n";
