<?php

// MANTICORE-ONLY (no Http\Server in php). The four var_dump blocks in the
// expected file are GENERATED by php's parse_str over the same query string
// (see the oracle command in the docblock of Http\nestedAssign); the flat line
// and the max_input_vars count are by hand. Ports scanned, never printed.

use function Async\async;
use function Async\spawn;

function listen(int $from): array<int, mixed>
{
    for ($p = $from; $p < $from + 60; $p = $p + 1) {
        $s = @stream_socket_server('tcp://127.0.0.1:' . $p);
        if ($s !== false) { stream_set_blocking($s, false); return [$s, $p]; }
    }
    return [false, 0];
}

function readOne(\Resource $c): string
{
    $buf = '';
    while (true) {
        $end = strpos($buf, "\r\n\r\n");
        if ($end !== false) {
            $len = 0;
            foreach (explode("\r\n", substr($buf, 0, $end)) as $line) {
                if (stripos($line, 'content-length:') === 0) { $len = (int)trim(substr($line, 15)); }
            }
            if (strlen($buf) >= $end + 4 + $len) { return substr($buf, $end + 4, $len); }
        }
        $chunk = fread($c, 4096);
        if ($chunk === '') { return ''; }
        $buf .= $chunk;
    }
}

function call(int $port, string $raw): string
{
    $c = fsockopen('127.0.0.1', $port);
    if ($c === false) { return 'CONNECT-FAILED'; }
    fwrite($c, $raw);
    $out = readOne($c);
    fclose($c);
    return $out;
}

$qs = "a[]=1&a[]=2&b[x][y]=3&c.d=4&e%5B0%5D=5&f=6&f=7&g[=8&h[a]b=9&i[0]=x&i[00]=y&j[-1]=z&k[]=1&k[q]=2&l=%2B+";

[$l1, $p1] = listen(50200);
[$l2, $p2] = listen(50260);
if ($l1 === false || $l2 === false) { echo "no free port\n"; return; }

$shapes = \Http\Server::onListener($l1)->acceptWait(0.02)->compat(true);
$capped = \Http\Server::onListener($l2)->acceptWait(0.02)->compat(true)->maxInputVars(1000);

async(function () use ($shapes, $capped, $p1, $p2, $qs) {
    spawn(function () use ($shapes) {
        $shapes->serve(function (\Http\Request $req): \Http\Response {
            ob_start();
            echo "query:\n"; var_dump($req->queryArray());
            echo "get:\n"; var_dump($_GET);
            echo "post:\n"; var_dump($req->postArray());
            echo "POST:\n"; var_dump($_POST);
            echo 'flat f=', $req->query('f'), ' deep=', $_GET['b']['x']['y'], ' count=', count($_GET), "\n";
            $s = ob_get_clean();
            return (new \Http\Response())->text($s === false ? '' : $s);
        });
    });
    spawn(function () use ($capped) {
        $capped->serve(function (\Http\Request $req): \Http\Response {
            return (new \Http\Response())->text('vars=' . count($_GET) . "\n");
        });
    });
    \Async\delay(0.05);

    echo call($p1, "POST /p?" . $qs . " HTTP/1.1\r\nHost: t\r\n"
        . "Content-Type: application/x-www-form-urlencoded\r\n"
        . 'Content-Length: ' . strlen($qs) . "\r\n\r\n" . $qs);

    $many = '';
    for ($i = 0; $i <= 1001; $i = $i + 1) {
        $many .= ($i === 0 ? '' : '&') . 'v' . $i . '=' . $i;
    }
    echo call($p2, "GET /c?" . $many . " HTTP/1.1\r\nHost: t\r\n\r\n");

    $shapes->stop();
    $capped->stop();
});
echo "done\n";
