<?php

// MANTICORE-ONLY (no Http\Server in php): a loopback server exercising
// Request::files()/allFiles() and the multipart branch of postArray() (Task
// 5). Bodies are hand-built with boundary `----mcb`, reusing the body()/part()
// helpers from http_multipart_parse.php. `split` dribbles the body 7 bytes at
// a time (usleep(1000) between writes, fiber-aware, so the reactor gets a turn)
// so the parser sees the delimiter split across socket reads. `bad` has no
// blank line ending a part's head, so parseAll() fails and the server answers
// 400 before the handler runs — Connection: close. `toobig` runs against a
// SECOND server with a tight uploadMaxFilesize, so the file parses but carries
// error=1. The expected output is written BY HAND; the two
// `var_dump($req->postArray())` blocks with nested keys are GENERATED by php:
// parse_str('a=1&b[x]=2', $r); var_dump($r) and
// parse_str('u[name]=Ada&u[age]=30', $r); var_dump($r).

use function Async\async;
use function Async\spawn;

final class Client
{
    private string $buf = '';

    public function __construct(private \Resource $c) {}

    public function send(string $raw): void { fwrite($this->c, $raw); }

    /** One complete response; body length taken from Content-Length. */
    public function readOne(): string
    {
        while (true) {
            $end = strpos($this->buf, "\r\n\r\n");
            if ($end !== false) {
                $head = substr($this->buf, 0, $end);
                $len = 0;
                foreach (explode("\r\n", $head) as $line) {
                    if (stripos($line, 'content-length:') === 0) {
                        $len = (int)trim(substr($line, 15));
                    }
                }
                $whole = $end + 4 + $len;
                if (strlen($this->buf) >= $whole) {
                    $out = substr($this->buf, 0, $whole);
                    $this->buf = substr($this->buf, $whole);
                    return $out;
                }
            }
            $chunk = fread($this->c, 4096);
            if ($chunk === '') {
                $out = $this->buf;
                $this->buf = '';
                return $out;
            }
            $this->buf .= $chunk;
        }
    }

    public function close(): void { fclose($this->c); }
}

function show(string $label, string $raw): void
{
    $end = strpos($raw, "\r\n\r\n");
    $head = $end === false ? $raw : substr($raw, 0, $end);
    $body = $end === false ? '' : substr($raw, $end + 4);
    $lines = explode("\r\n", $head);
    echo $label, ': ', $lines[0], ' body=', $body, "\n";
}

function part(string $disp, string $data, string $type = ''): string
{
    $h = 'Content-Disposition: form-data; ' . $disp . "\r\n";
    if ($type !== '') { $h .= 'Content-Type: ' . $type . "\r\n"; }
    return $h . "\r\n" . $data;
}

function body(array<int, string> $parts): string
{
    $b = '';
    foreach ($parts as $p) { $b .= "------mcb\r\n" . $p . "\r\n"; }
    return $b . "------mcb--\r\n";
}

function post(string $path, string $b): string
{
    return 'POST ' . $path . " HTTP/1.1\r\nHost: t\r\nContent-Type: multipart/form-data; boundary=----mcb\r\n"
        . 'Content-Length: ' . strlen($b) . "\r\n\r\n" . $b;
}

function multipartHandler(\Http\Request $req): \Http\Response
{
    if ($req->path === '/throws') {
        foreach ($req->allFiles() as $f) {
            $f->contents();
        }
        throw new \RuntimeException('boom');
    }
    $out = 'count=' . count($req->allFiles()) . "\n";
    foreach ($req->allFiles() as $f) {
        $out = $out . 'field=' . $f->field . ' name=' . $f->name . ' type=' . $f->type
            . ' size=' . $f->size . ' error=' . $f->error . ' md5=' . md5($f->contents()) . "\n";
    }
    ob_start();
    var_dump($req->postArray());
    $dump = ob_get_clean();
    $out = $out . ($dump === false ? '' : $dump);
    foreach ($req->allFiles() as $f) {
        if ($f->tmpName !== '') { @unlink($f->tmpName); }
    }
    return (new \Http\Response())->text($out);
}

$port = 0;
$listener = false;
for ($p = 49940; $p < 50020; $p = $p + 1) {
    $s = @stream_socket_server('tcp://127.0.0.1:' . $p);
    if ($s !== false) {
        $listener = $s;
        $port = $p;
        break;
    }
}
if ($listener === false) {
    echo "no free port\n";
    return;
}
stream_set_blocking($listener, false);

$port2 = 0;
$listener2 = false;
for ($p = 50020; $p < 50100; $p = $p + 1) {
    $s = @stream_socket_server('tcp://127.0.0.1:' . $p);
    if ($s !== false) {
        $listener2 = $s;
        $port2 = $p;
        break;
    }
}
if ($listener2 === false) {
    echo "no free port\n";
    return;
}
stream_set_blocking($listener2, false);

$server = \Http\Server::onListener($listener)
    ->serverName('')
    ->acceptWait(0.02);

$server2 = \Http\Server::onListener($listener2)
    ->serverName('')
    ->acceptWait(0.02)
    ->uploadMaxFilesize(100);

async(function () use ($server, $server2, $port, $port2) {
    spawn(function () use ($server) {
        $server->serve(function (\Http\Request $req): \Http\Response {
            return multipartHandler($req);
        });
    });
    spawn(function () use ($server2) {
        $server2->serve(function (\Http\Request $req): \Http\Response {
            return multipartHandler($req);
        });
    });

    \Async\delay(0.05);

    $c = new Client(fsockopen('127.0.0.1', $port));

    // plain: two text fields (one nested) + one file.
    $b1 = body([part('name="a"', '1'), part('name="b[x]"', '2'),
        part('name="f"; filename="hello.txt"', 'hello world', 'text/plain')]);
    $c->send(post('/upload', $b1));
    show('plain', $c->readOne());

    // array: two files under the same field name f[].
    $b2 = body([part('name="f[]"; filename="a.txt"', 'AAA'), part('name="f[]"; filename="b.txt"', 'BBBB')]);
    $c->send(post('/upload', $b2));
    show('array', $c->readOne());

    // nested: two nested text fields + one file under a nested field name.
    $b3 = body([part('name="u[name]"', 'Ada'), part('name="u[age]"', '30'),
        part('name="u[avatar]"; filename="avatar.png"', 'PNGDATA', 'image/png')]);
    $c->send(post('/upload', $b3));
    show('nested', $c->readOne());

    // split: the body dribbled 7 bytes at a time — the delimiter straddles reads.
    $b4 = body([part('name="f"; filename="c.txt"', 'split content here', 'text/plain')]);
    $head4 = 'POST /upload HTTP/1.1' . "\r\nHost: t\r\nContent-Type: multipart/form-data; boundary=----mcb\r\n"
        . 'Content-Length: ' . strlen($b4) . "\r\n\r\n";
    $c->send($head4);
    $pos = 0;
    $n = strlen($b4);
    while ($pos < $n) {
        $chunk = substr($b4, $pos, 7);
        $c->send($chunk);
        $pos = $pos + strlen($chunk);
        usleep(1000);
    }
    show('split', $c->readOne());

    // bad: a part with no blank line between its head and its data — parseAll()
    // fails, the server answers 400 before the handler runs.
    $b5 = '------mcb' . "\r\n" . 'Content-Disposition: form-data; name="a"' . "\r\n" . '1' . "\r\n" . '------mcb--' . "\r\n";
    $c->send(post('/upload', $b5));
    show('bad', $c->readOne());
    $c->close();

    // nobody: a GET carries no body — allFiles() and postArray() are empty.
    $c2 = new Client(fsockopen('127.0.0.1', $port));
    $c2->send("GET /upload HTTP/1.1\r\nHost: t\r\n\r\n");
    show('nobody', $c2->readOne());
    $c2->close();

    // throws: the handler reads a file, then throws — pinned as a 500.
    $c3 = new Client(fsockopen('127.0.0.1', $port));
    $b6 = body([part('name="f"; filename="d.txt"', 'doomed', 'text/plain')]);
    $c3->send(post('/throws', $b6));
    show('throws', $c3->readOne());
    $c3->close();

    // toobig: a second server with uploadMaxFilesize(100) — the file parses,
    // but its error is 1 (UPLOAD_ERR_INI_SIZE).
    $c4 = new Client(fsockopen('127.0.0.1', $port2));
    $b7 = body([part('name="f"; filename="big.bin"', str_repeat('A', 150), 'application/octet-stream')]);
    $c4->send(post('/upload', $b7));
    show('toobig', $c4->readOne());
    $c4->close();

    $server->stop();
    $server2->stop();
    $st = $server->stats();
    $st2 = $server2->stats();
    echo 'served=', $st['served'], ' errors=', $st['errors'],
        ' served2=', $st2['served'], ' errors2=', $st2['errors'], "\n";
});

echo "done\n";
