<?php

/**
 * mbstring's encoding layer: name resolution and the codecs behind every
 * encoding that is not UTF-8.
 *
 * Every codec meets the others in ONE interchange form, "marked UTF-8":
 * generalized UTF-8 — a surrogate codepoint is spelled like any other, because
 * UCS-2 / UCS-4 pass surrogates through and Zend's UTF-8 encoder writes them —
 * in which each malformed input unit is the single byte "\xFF". Valid UTF-8
 * never contains 0xFF, so to every UTF-8 walker a marker is exactly one unit,
 * and in a search it matches only another marker, which is how Zend's decoded
 * error units compare. One escape rides on top for a conversion out of UCS-4,
 * whose code units may exceed U+10FFFF and are still characters to Zend (they
 * pass through to UCS-4 and are unrepresentable elsewhere): "\xFE" + the value
 * as 4 big-endian bytes. Only `__mc_mb_dec8(..., true)` produces it.
 *
 * A KIND says which fast paths apply (see Mbstring.php): 0 UTF-8, 1 single-byte
 * (a generated byte → codepoint table), 2 fixed-width UCS-2 / UCS-4 / UTF-32
 * (Zend counts and cuts those by width, on the raw bytes), 3 everything else —
 * UTF-16 in PHP, the CJK and stateful encodings through the host iconv.
 */

/** @return array<string,string> lowercase name / MIME name / alias → canonical name */
function __mc_mb_names(): array
{
    static $names = [];
    if ($names !== []) { return $names; }
    $t = [];
    $list = \__mc_mb_list();
    $mime = \__mc_mb_mime_table();
    // Zend matches every NAME first, then every MIME name, then every alias.
    foreach ($list as $canon) { $t[\strtolower($canon)] = $canon; }
    foreach ($list as $canon) {
        $m = \strtolower($mime[$canon]);
        if ($m !== "" && !isset($t[$m])) { $t[$m] = $canon; }
    }
    foreach (\__mc_mb_alias_table() as $canon => $aliases) {
        foreach ($aliases as $a) {
            $k = \strtolower($a);
            if (!isset($t[$k])) { $t[$k] = $canon; }
        }
    }
    $names = $t;
    return $names;
}

/** Canonical name of an encoding mbstring knows, or "". */
function __mc_mb_canon(string $encoding): string
{
    $names = \__mc_mb_names();
    $k = \strtolower($encoding);
    return isset($names[$k]) ? $names[$k] : "";
}

/** @return array<string,int[]> */
function __mc_mb_sb_tables(): array
{
    static $t = [];
    if ($t === []) { $t = \__mc_mb_sbcs_tables(); }
    return $t;
}

/** Code-unit width of a fixed-width encoding (UCS-2 2, UCS-4 / UTF-32 4), else 0. */
function __mc_mb_width(string $enc): int
{
    if (\str_starts_with($enc, "UCS-2")) { return 2; }
    if (\str_starts_with($enc, "UCS-4") || \str_starts_with($enc, "UTF-32")) { return 4; }
    return 0;
}

function __mc_mb_kind_of(string $enc): int
{
    if ($enc === "UTF-8" || \str_starts_with($enc, "UTF-8-Mobile")) { return 0; }
    // UUENCODE carries Zend's single-byte flag: counted and cut as raw bytes.
    if ($enc === "UUENCODE" || isset(\__mc_mb_sb_tables()[$enc])) { return 1; }
    if (\__mc_mb_width($enc) > 0) { return 2; }
    return 3;
}

/** Whether `$enc` is decoded/encoded by the PHP code here (the UCS / UTF-16 / UTF-32 family). */
function __mc_mb_is_wide(string $enc): bool
{
    return \__mc_mb_width($enc) > 0 || \str_starts_with($enc, "UTF-16");
}

// ── marked UTF-8 ─────────────────────────────────────────────────────────────

/**
 * Units of a marked UTF-8 string: codepoints, -1 per marker.
 * @return int[]
 */
function __mc_mb_units(string $u): array
{
    $out = [];
    $n = \strlen($u);
    $i = 0;
    while ($i < $n) {
        $b = \ord($u[$i]);
        if ($b < 0x80) {
            $out[] = $b;
            $i = $i + 1;
        } elseif ($b === 0xFF) {
            $out[] = -1;
            $i = $i + 1;
        } elseif ($b === 0xFE) {
            $out[] = \__mc_mb_unit($u, $i + 1, 4, false);
            $i = $i + 5;
        } else {
            $len = $b >= 0xF0 ? 4 : ($b >= 0xE0 ? 3 : 2);
            $out[] = \__mc_mb_cp(0, $u, $i, $i + $len);
            $i = $i + $len;
        }
    }
    return $out;
}

/** Decode `$s` in `$enc` to marked UTF-8; `$big` keeps UCS-4 values past U+10FFFF (escaped) instead of marking them. */
function __mc_mb_dec8(string $enc, string $s, bool $big = false): string
{
    if ($enc === "BASE64") { return \__mc_mb_base64_dec8($s); }
    if ($enc === "Quoted-Printable") { return \__mc_mb_qprint_dec8($s); }
    if ($enc === "UUENCODE") { return \__mc_mb_uuencode_dec8($s); }
    if ($enc === "HTML-ENTITIES") { return \__mc_mb_htmlent_dec8($s); }
    $kind = \__mc_mb_kind_of($enc);
    if ($kind === 0) { return \__mc_mb_scrub_range(0, $s, 0, \strlen($s), "\xFF"); }
    if ($kind === 1) { return \__mc_mb_sb_dec8($enc, $s); }
    if (\__mc_mb_is_wide($enc)) { return \__mc_mb_wide_dec8($enc, $s, $big); }
    if ($enc === "UTF-7" || $enc === "UTF7-IMAP") { return \__mc_mb_utf7_dec8($s, $enc === "UTF7-IMAP"); }
    return \__mc_mb_iconv_dec8($enc, $s);
}

/**
 * Encode marked UTF-8 `$u` into `$enc`. A marker becomes the substitute for bad
 * input, a codepoint `$enc` cannot spell the substitute for an unrepresentable
 * character — or, `$strict`, the whole call answers null.
 */
function __mc_mb_enc8(string $enc, string $u, bool $strict = false): ?string
{
    if ($enc === "BASE64") { return \__mc_mb_base64_enc(\__mc_mb_raw_units($u)); }
    if ($enc === "Quoted-Printable") { return \__mc_mb_qprint_enc(\__mc_mb_raw_units($u)); }
    if ($enc === "UUENCODE") { return \__mc_mb_uuencode_enc(\__mc_mb_raw_units($u)); }
    if ($enc === "HTML-ENTITIES") { return \__mc_mb_htmlent_enc(\__mc_mb_raw_units($u)); }
    $kind = \__mc_mb_kind_of($enc);
    if ($kind === 0 && !\str_contains($u, "\xFE")) {
        if (!\str_contains($u, "\xFF")) { return $u; }
        if ($strict) { return null; }
        return \str_replace("\xFF", \__mc_mb_bad_bytes($enc), $u);
    }
    if ($enc === "UTF-7" || $enc === "UTF7-IMAP") { return \__mc_mb_utf7_enc(\__mc_mb_units($u), $enc === "UTF7-IMAP", $strict); }
    if ($kind === 3 && !\__mc_mb_is_wide($enc)) { return \__mc_mb_iconv_enc8($enc, $u, $strict); }
    $out = "";
    foreach (\__mc_mb_units($u) as $cp) {
        $b = $cp < 0 ? null : \__mc_mb_enc_cp($enc, $kind, $cp);
        if ($b === null) {
            if ($strict) { return null; }
            $b = $cp < 0 ? \__mc_mb_bad_bytes($enc) : \__mc_mb_unrep_bytes($enc, $cp);
        }
        $out = $out . $b;
    }
    return $out;
}

/**
 * Zend's mb_fast_convert. Converting TO Base64 / QPrint encodes the raw input
 * bytes (the source is read as 8bit), converting FROM Base64 / QPrint / UUENCODE
 * yields raw bytes (the target becomes 8bit). `$marker` is the BADUTF8 mode Zend
 * searches in: every malformed or unencodable unit is one "\xFF" (targets UTF-8
 * or, by the rule above, 8bit).
 */
function __mc_mb_fast(string $s, string $from, string $to, bool $marker = false): string
{
    if ($s === "") { return ""; }
    if ($to === "BASE64" || $to === "Quoted-Printable") {
        $from = "8bit";
    } elseif ($from === "BASE64" || $from === "Quoted-Printable" || $from === "UUENCODE") {
        $to = "8bit";
    }
    $u = \__mc_mb_dec8($from, $s, !$marker);
    if (!$marker) { return (string)\__mc_mb_enc8($to, $u); }
    if ($to !== "8bit") { return $u; }
    $out = "";
    foreach (\__mc_mb_units($u) as $w) { $out = $out . ($w < 0 || $w > 0xFF ? "\xFF" : \chr($w)); }
    return $out;
}

/** Bytes of `$cp` in a single-byte or wide `$enc`, or null when it has none. */
function __mc_mb_enc_cp(string $enc, int $kind, int $cp): ?string
{
    if ($kind === 0) { return $cp <= 0x10FFFF ? \__mc_mb_u8_chr($cp) : null; }
    if ($kind === 1) {
        $fix = \__mc_mb_sb_fix($enc);
        if (isset($fix[$cp])) { return $fix[$cp] < 0 ? null : \chr($fix[$cp]); }
        if ($cp < 0x80) { return \chr($cp); }
        $rev = \__mc_mb_sb_rev($enc);
        return isset($rev[$cp]) ? \chr($rev[$cp]) : null;
    }
    $le = \str_ends_with($enc, "LE");
    $w = \__mc_mb_width($enc);
    if ($w === 4) {
        if ($cp > 0x10FFFF && \str_starts_with($enc, "UTF-32")) { return null; }
        return \__mc_mb_pack($cp, 4, $le);
    }
    if ($w === 2) { return $cp > 0xFFFF ? null : \__mc_mb_pack($cp, 2, $le); }
    if ($cp < 0x10000) { return \__mc_mb_pack($cp, 2, $le); }
    if ($cp > 0x10FFFF) { return null; }
    $v = $cp - 0x10000;
    return \__mc_mb_pack(0xD800 | ($v >> 10), 2, $le) . \__mc_mb_pack(0xDC00 | ($v & 0x3FF), 2, $le);
}

/** `$v` as a `$w`-byte big- or little-endian unit. */
function __mc_mb_pack(int $v, int $w, bool $le): string
{
    $s = "";
    $k = $w - 1;
    while ($k >= 0) {
        $s = $s . \chr(($v >> ($k * 8)) & 0xFF);
        $k = $k - 1;
    }
    return $le ? \strrev($s) : $s;
}

/** What one malformed input unit becomes in `$enc`. */
function __mc_mb_bad_bytes(string $enc): string
{
    $st = \__mc_mb_subst();
    if ($st[0] === 1) { return ""; }
    $b = \__mc_mb_enc8($enc, \__mc_mb_u8_chr($st[1]), true);
    if ($b !== null) { return $b; }
    return $st[0] === 0 ? (string)\__mc_mb_enc8($enc, "?", true) : "";
}

/**
 * The substitute for `$cp` (-1 = bad input) as codepoints, for an encoder that
 * must emit it in-stream (a stateful one). Zend's mb_illegal_marker.
 * @return int[]
 */
function __mc_mb_subst_cps(int $cp): array
{
    $st = \__mc_mb_subst();
    if ($st[0] === 1) { return []; }
    if ($cp < 0 || $st[0] === 0) { return [$st[1]]; }
    $text = $st[0] === 2 ? "U+" . \strtoupper(\dechex($cp)) : "&#x" . \strtoupper(\dechex($cp)) . ";";
    $out = [];
    $n = \strlen($text);
    $i = 0;
    while ($i < $n) {
        $out[] = \ord($text[$i]);
        $i = $i + 1;
    }
    return $out;
}

/** What codepoint `$cp`, which `$enc` cannot spell, becomes. */
function __mc_mb_unrep_bytes(string $enc, int $cp): string
{
    $st = \__mc_mb_subst();
    if ($st[0] === 1) { return ""; }
    if ($st[0] === 2) { return (string)\__mc_mb_enc8($enc, "U+" . \strtoupper(\dechex($cp)), true); }
    if ($st[0] === 3) { return (string)\__mc_mb_enc8($enc, "&#x" . \strtoupper(\dechex($cp)) . ";", true); }
    $b = \__mc_mb_enc8($enc, \__mc_mb_u8_chr($st[1]), true);
    return $b !== null ? $b : (string)\__mc_mb_enc8($enc, "?", true);
}

// ── single-byte ──────────────────────────────────────────────────────────────

function __mc_mb_sb_dec8(string $enc, string $s): string
{
    $n = \strlen($s);
    $i = 0;
    while ($i < $n && \ord($s[$i]) < 0x80) { $i = $i + 1; }
    if ($i === $n) { return $s; }
    $tab = \__mc_mb_sb_tables()[$enc];
    $out = \substr($s, 0, $i);
    while ($i < $n) {
        $b = \ord($s[$i]);
        if ($b < 0x80) {
            $out = $out . $s[$i];
        } else {
            $cp = $tab[$b - 0x80];
            $out = $out . ($cp < 0 ? "\xFF" : \__mc_mb_u8_chr($cp));
        }
        $i = $i + 1;
    }
    return $out;
}

/** @return array<int,int> Zend's encoder answers that differ from the mirror of the decode table */
function __mc_mb_sb_fix(string $enc): array
{
    static $all = [];
    static $loaded = false;
    if (!$loaded) {
        $all = \__mc_mb_sbcs_rev_fix();
        $loaded = true;
    }
    return isset($all[$enc]) ? $all[$enc] : [];
}

/** Lead-byte length table of `$enc` (one digit per byte), "" when Zend walks it by decoding. */
function __mc_mb_mblen_table(string $enc): string
{
    static $all = [];
    static $loaded = false;
    if (!$loaded) {
        $all = \__mc_mb_mblen_tables();
        $loaded = true;
    }
    return isset($all[$enc]) ? $all[$enc] : "";
}

/** @return array<int,int> codepoint → byte, high half only */
function __mc_mb_sb_rev(string $enc): array
{
    static $cache = [];
    if (isset($cache[$enc])) { return $cache[$enc]; }
    $rev = [];
    $b = 0x80;
    foreach (\__mc_mb_sb_tables()[$enc] as $cp) {
        if ($cp >= 0 && !isset($rev[$cp])) { $rev[$cp] = $b; }
        $b = $b + 1;
    }
    $cache[$enc] = $rev;
    return $rev;
}

// ── UCS-2 / UCS-4 / UTF-16 / UTF-32 ─────────────────────────────────────────

/** Unsigned `$w`-byte unit at `$i`. */
function __mc_mb_unit(string $s, int $i, int $w, bool $le): int
{
    $v = 0;
    $k = 0;
    while ($k < $w) {
        $b = \ord($s[$le ? $i + $w - 1 - $k : $i + $k]);
        $v = ($v << 8) | $b;
        $k = $k + 1;
    }
    return $v;
}

/**
 * Zend's rules: a name without BE/LE honours a leading byte-order mark (and
 * drops it) and is big-endian otherwise; UTF-16 pairs surrogates and marks a
 * lone one; UTF-32 marks a surrogate or anything past U+10FFFF, UCS-4 only the
 * latter; a trailing partial unit is one malformed unit.
 */
function __mc_mb_wide_dec8(string $enc, string $s, bool $big = false): string
{
    $utf16 = \str_starts_with($enc, "UTF-16");
    $w = $utf16 ? 2 : \__mc_mb_width($enc);
    $le = \str_ends_with($enc, "LE");
    $n = \strlen($s);
    $i = 0;
    if (!$le && !\str_ends_with($enc, "BE") && $n >= $w) {
        $bom = \substr($s, 0, $w);
        if ($bom === ($w === 2 ? "\xFE\xFF" : "\x00\x00\xFE\xFF")) {
            $i = $w;
        } elseif ($bom === ($w === 2 ? "\xFF\xFE" : "\xFF\xFE\x00\x00")) {
            $i = $w;
            $le = true;
        }
    }
    $utf32 = \str_starts_with($enc, "UTF-32");
    $out = "";
    while ($i + $w <= $n) {
        $u = \__mc_mb_unit($s, $i, $w, $le);
        $i = $i + $w;
        if ($utf16 && $u >= 0xD800 && $u <= 0xDFFF) {
            if ($u <= 0xDBFF && $i + 2 <= $n) {
                $lo = \__mc_mb_unit($s, $i, 2, $le);
                if ($lo >= 0xDC00 && $lo <= 0xDFFF) {
                    $out = $out . \__mc_mb_u8_chr(0x10000 + (($u - 0xD800) << 10) + ($lo - 0xDC00));
                    $i = $i + 2;
                    continue;
                }
            }
            $out = $out . "\xFF";
            continue;
        }
        if ($w === 4 && ($u > 0x10FFFF || ($utf32 && $u >= 0xD800 && $u <= 0xDFFF))) {
            $out = $out . ($big && !$utf32 ? "\xFE" . \__mc_mb_pack($u, 4, false) : "\xFF");
            continue;
        }
        $out = $out . \__mc_mb_u8_chr($u);
    }
    if ($i < $n) { $out = $out . "\xFF"; }
    return $out;
}

/**
 * Raw code units of a fixed-width string: UCS-2 / UCS-4 values as they stand
 * (any 32-bit value is one character to Zend — only a conversion to Unicode
 * rejects past U+10FFFF), UTF-32 marking a surrogate or a value past U+10FFFF;
 * -1 for a partial trailing unit. A name without BE/LE drops a leading
 * byte-order mark and follows it.
 * @return int[]
 */
function __mc_mb_fixed_units(string $enc, string $s): array
{
    $w = \__mc_mb_width($enc);
    $le = \str_ends_with($enc, "LE");
    $utf32 = \str_starts_with($enc, "UTF-32");
    $n = \strlen($s);
    $i = 0;
    if (!$le && !\str_ends_with($enc, "BE") && $n >= $w) {
        $bom = \substr($s, 0, $w);
        if ($bom === ($w === 2 ? "\xFE\xFF" : "\x00\x00\xFE\xFF")) {
            $i = $w;
        } elseif ($bom === ($w === 2 ? "\xFF\xFE" : "\xFF\xFE\x00\x00")) {
            $i = $w;
            $le = true;
        }
    }
    $out = [];
    while ($i + $w <= $n) {
        $u = \__mc_mb_unit($s, $i, $w, $le);
        $out[] = $utf32 && ($u > 0x10FFFF || ($u >= 0xD800 && $u <= 0xDFFF)) ? -1 : $u;
        $i = $i + $w;
    }
    if ($i < $n) { $out[] = -1; }
    return $out;
}

// ── host iconv (CJK, stateful and the rest) ─────────────────────────────────

/**
 * The host iconv's name for `$enc`, "" when this host has no converter. Hosts
 * spell these differently (glibc, macOS libiconv, musl), so each encoding lists
 * its candidates in order; the first one iconv_open accepts wins. A fallback
 * that is not the same table (eucJP-win → EUC-JP) trades exactness for having
 * a converter at all.
 */
function __mc_mb_iconv_name(string $enc): string
{
    static $cache = [];
    if (isset($cache[$enc])) { return $cache[$enc]; }
    $cands = ["UTF-8"];
    if ($enc === "EUC-JP") { $cands = ["EUC-JP"]; }
    elseif ($enc === "SJIS") { $cands = ["SHIFT_JIS", "SJIS"]; }
    elseif ($enc === "eucJP-win" || $enc === "CP51932") { $cands = ["EUC-JP-MS", "CP51932", "EUC-JP"]; }
    elseif ($enc === "EUC-JP-2004") { $cands = ["EUC-JISX0213", "EUC-JP"]; }
    elseif ($enc === "SJIS-2004") { $cands = ["SHIFT_JISX0213", "SHIFT_JIS"]; }
    elseif ($enc === "SJIS-mac") { $cands = ["MACJAPANESE", "SHIFT_JIS"]; }
    elseif ($enc === "CP932" || $enc === "SJIS-win" || \str_starts_with($enc, "SJIS-Mobile")) {
        $cands = ["CP932", "WINDOWS-31J", "SHIFT_JIS"];
    }
    elseif ($enc === "JIS" || $enc === "ISO-2022-JP" || \str_starts_with($enc, "ISO-2022-JP-MOBILE")) {
        $cands = ["ISO-2022-JP"];
    }
    elseif ($enc === "ISO-2022-JP-MS" || \str_starts_with($enc, "CP5022")) {
        $cands = ["CP50221", "ISO-2022-JP-MS", "ISO-2022-JP"];
    }
    elseif ($enc === "ISO-2022-JP-2004") { $cands = ["ISO-2022-JP-3", "ISO-2022-JP"]; }
    elseif (\str_starts_with($enc, "GB18030")) { $cands = ["GB18030"]; }
    elseif ($enc === "EUC-CN") { $cands = ["EUC-CN", "GB2312"]; }
    elseif ($enc === "CP936") { $cands = ["CP936", "GBK"]; }
    elseif ($enc === "HZ") { $cands = ["HZ", "HZ-GB-2312"]; }
    elseif ($enc === "EUC-TW") { $cands = ["EUC-TW"]; }
    elseif ($enc === "BIG-5") { $cands = ["BIG5", "BIG-5"]; }
    elseif ($enc === "CP950") { $cands = ["CP950", "BIG5"]; }
    elseif ($enc === "EUC-KR") { $cands = ["EUC-KR"]; }
    elseif ($enc === "UHC") { $cands = ["CP949", "UHC", "EUC-KR"]; }
    elseif ($enc === "ISO-2022-KR") { $cands = ["ISO-2022-KR"]; }
    else { $cands = []; }
    $found = "";
    foreach ($cands as $c) {
        $cd = \Runtime\Iconv\iconv_open("UTF-8", $c);
        if ($cd === -1 || $cd === 0 || $cd === 4294967295) { continue; }
        \Runtime\Iconv\iconv_close($cd);
        $found = $c;
        break;
    }
    $cache[$enc] = $found;
    return $found;
}

function __mc_mb_iconv_failed(int $cd): bool
{
    return $cd === -1 || $cd === 0 || $cd === 4294967295;
}

/** Open a descriptor for `$enc` in the given direction; throws when the host has none. */
function __mc_mb_iconv_open(string $enc, bool $toUtf8): int
{
    $name = \__mc_mb_iconv_name($enc);
    if ($name === "") {
        throw new \Error("mbstring: no converter for encoding \"" . $enc . "\" on this host");
    }
    $cd = $toUtf8 ? \Runtime\Iconv\iconv_open("UTF-8", $name) : \Runtime\Iconv\iconv_open($name, "UTF-8");
    if (\__mc_mb_iconv_failed($cd)) {
        throw new \Error("mbstring: no converter for encoding \"" . $enc . "\" on this host");
    }
    return $cd;
}

/**
 * Whether the host iconv can ENCODE into `$enc`. `__mc_mb_iconv_name` probes the
 * decoding direction only, and musl decodes GB18030 / GBK / BIG5 / EUC-KR / CP949
 * but encodes none of them.
 */
function __mc_mb_iconv_can_enc(string $enc): bool
{
    static $cache = [];
    if (isset($cache[$enc])) { return $cache[$enc]; }
    $name = \__mc_mb_iconv_name($enc);
    $ok = false;
    if ($name !== "") {
        $cd = \Runtime\Iconv\iconv_open($name, "UTF-8");
        if (!\__mc_mb_iconv_failed($cd)) {
            \Runtime\Iconv\iconv_close($cd);
            $ok = true;
        }
    }
    $cache[$enc] = $ok;
    return $ok;
}

/**
 * Codepoint => bytes for `$enc`, built once by running the host's DECODER over
 * every one- and two-byte sequence (and GB18030's four-byte BMP range) — the
 * encoder a decode-only host lacks. The first (lowest) sequence of a codepoint
 * wins, as libmbfl's tables prefer the canonical one.
 * @return array<int,string>
 */
function __mc_mb_inv_table(string $enc): array
{
    static $tables = [];
    if (isset($tables[$enc])) { return $tables[$enc]; }
    $cd = \__mc_mb_iconv_open($enc, true);
    $cap = 64;
    $cells = \__mc_mb_iconv_cells($cap);
    $map = [];
    $seqs = [];
    for ($b = 0x80; $b <= 0xFF; $b++) { $seqs[] = \chr($b); }
    for ($l = 0x81; $l <= 0xFE; $l++) {
        for ($t = 0x40; $t <= 0xFE; $t++) {
            if ($t !== 0x7F) { $seqs[] = \chr($l) . \chr($t); }
        }
    }
    if (\str_starts_with($enc, "GB18030")) {
        for ($b1 = 0x81; $b1 <= 0x84; $b1++) {
            for ($b2 = 0x30; $b2 <= 0x39; $b2++) {
                for ($b3 = 0x81; $b3 <= 0xFE; $b3++) {
                    for ($b4 = 0x30; $b4 <= 0x39; $b4++) { $seqs[] = \chr($b1) . \chr($b2) . \chr($b3) . \chr($b4); }
                }
            }
        }
    }
    foreach ($seqs as $seq) {
        $u = \__mc_mb_iconv_feed($cd, $seq, 0, $cells, $cap);
        if ($u === "" || \peek_i64($cells[5], 0) !== \strlen($seq)) { continue; }
        $n = \__mc_mb_u8_step($u, 0, \strlen($u));
        if ($n !== \strlen($u)) { continue; }
        $cp = \__mc_mb_cp(0, $u, 0, $n);
        if ($cp >= 0x80 && !isset($map[$cp])) { $map[$cp] = $seq; }
    }
    \__mc_mb_iconv_free($cd, $cells);
    $tables[$enc] = $map;
    return $map;
}

/** GB18030's four-byte form of a supplementary codepoint — linear, no table. */
function __mc_mb_gb18030_supp(int $cp): string
{
    $v = $cp - 0x10000;
    $b4 = $v % 10; $v = \intdiv($v, 10);
    $b3 = $v % 126; $v = \intdiv($v, 126);
    $b2 = $v % 10; $b1 = \intdiv($v, 10);
    return \chr(0x90 + $b1) . \chr(0x30 + $b2) . \chr(0x81 + $b3) . \chr(0x30 + $b4);
}

/**
 * One codepoint in `$enc` through the inverted table, null when it has no spelling.
 * @param array<int,string> $map
 */
function __mc_mb_inv_cp(string $enc, array $map, int $cp): ?string
{
    if ($cp < 0x80) { return \chr($cp); }
    if (isset($map[$cp])) { return $map[$cp]; }
    if ($cp >= 0x10000 && $cp <= 0x10FFFF && \str_starts_with($enc, "GB18030")) { return \__mc_mb_gb18030_supp($cp); }
    return null;
}

/** `__mc_mb_iconv_enc8` for a host that can decode `$enc` but not encode it. */
function __mc_mb_inv_enc8(string $enc, string $u, bool $strict): ?string
{
    $map = \__mc_mb_inv_table($enc);
    $out = "";
    foreach (\__mc_mb_units($u) as $cp) {
        $b = $cp < 0 ? null : \__mc_mb_inv_cp($enc, $map, $cp);
        if ($b === null) {
            if ($strict) { return null; }
            $b = "";
            foreach (\__mc_mb_iconv_subst($cp) as $piece) {
                $pb = "";
                $ok = true;
                foreach (\__mc_mb_units($piece) as $pc) {
                    $x = $pc < 0 ? null : \__mc_mb_inv_cp($enc, $map, $pc);
                    if ($x === null) { $ok = false; break; }
                    $pb = $pb . $x;
                }
                if ($ok) { $b = $pb; break; }
            }
        }
        $out = $out . $b;
    }
    return $out;
}

/**
 * Feed `$in` (from byte `$from`) through `$cd` until it is consumed or iconv
 * stops on a sequence it cannot convert; `$cells` holds the four pointer / length
 * scratch words and the output buffer. Returns the output; the byte offset where
 * it stopped is left in `$cells[5]` (`strlen($in)` when all was consumed).
 * An empty `$in` flushes the shift state.
 * @param array<int,\Ffi\Ptr> $cells
 */
function __mc_mb_iconv_feed(int $cd, string $in, int $from, array $cells, int $cap): string
{
    $n = \strlen($in) - $from;
    $inBuf = \Runtime\Libc\malloc($n > 0 ? $n : 1);
    \__mc_iconv_store($inBuf, \substr($in, $from));
    \poke_i64($cells[0], 0, $n > 0 ? \ptr_to_int($inBuf) : 0);
    \poke_i64($cells[1], 0, $n);
    $out = "";
    while (true) {
        $before = \peek_i64($cells[1], 0);
        \poke_i64($cells[2], 0, \ptr_to_int($cells[4]));
        \poke_i64($cells[3], 0, $cap);
        $r = \Runtime\Iconv\iconv_convert($cd, $cells[0], $cells[1], $cells[2], $cells[3]);
        $written = $cap - \peek_i64($cells[3], 0);
        if ($written > 0) { $out = $out . \__mc_iconv_read($cells[4], $written); }
        if ($r !== -1 && $r !== 4294967295) {
            if ($r > 0) { \poke_i64($cells[6], 0, \peek_i64($cells[6], 0) + $r); }
            break;
        }
        $left = \peek_i64($cells[1], 0);
        if ($left <= 0) { break; }
        if ($left < $before || $written > 0) { continue; }
        break;
    }
    $left = \peek_i64($cells[1], 0);
    \Runtime\Libc\free($inBuf);
    \poke_i64($cells[5], 0, \strlen($in) - $left);
    return $out;
}

/** @return array<int,\Ffi\Ptr> the six scratch cells + output buffer (index 4) */
function __mc_mb_iconv_cells(int $cap): array
{
    $cells = [];
    $cells[0] = \Runtime\Libc\malloc(8);
    $cells[1] = \Runtime\Libc\malloc(8);
    $cells[2] = \Runtime\Libc\malloc(8);
    $cells[3] = \Runtime\Libc\malloc(8);
    $cells[4] = \Runtime\Libc\malloc($cap);
    $cells[5] = \Runtime\Libc\malloc(8);
    $cells[6] = \Runtime\Libc\malloc(8);
    \poke_i64($cells[6], 0, 0);
    return $cells;
}

/** @param array<int,\Ffi\Ptr> $cells */
function __mc_mb_iconv_free(int $cd, array $cells): void
{
    foreach ($cells as $c) { \Runtime\Libc\free($c); }
    \Runtime\Iconv\iconv_close($cd);
}

function __mc_mb_iconv_dec8(string $enc, string $s): string
{
    if ($s === "") { return ""; }
    $cd = \__mc_mb_iconv_open($enc, true);
    $cap = 4096;
    $cells = \__mc_mb_iconv_cells($cap);
    $n = \strlen($s);
    $out = "";
    $at = 0;
    while ($at < $n) {
        $out = $out . \__mc_mb_iconv_feed($cd, $s, $at, $cells, $cap);
        $at = \peek_i64($cells[5], 0);
        if ($at < $n) {
            $out = $out . "\xFF";
            $at = $at + 1;
        }
    }
    \__mc_mb_iconv_free($cd, $cells);
    return $out;
}

function __mc_mb_iconv_enc8(string $enc, string $u, bool $strict): ?string
{
    if (!\__mc_mb_iconv_can_enc($enc)) { return \__mc_mb_inv_enc8($enc, $u, $strict); }
    $cd = \__mc_mb_iconv_open($enc, false);
    $cap = 4096;
    $cells = \__mc_mb_iconv_cells($cap);
    $out = \__mc_mb_iconv_enc8_run($cd, $cells, $cap, $u, $strict);
    $irreversible = \peek_i64($cells[6], 0);
    \__mc_mb_iconv_free($cd, $cells);
    if ($out === null) { return null; }
    // A host that substitutes instead of failing (musl writes '*' and counts it
    // as irreversible) hides which character it could not spell: go again one
    // character at a time so each one gets php's substitute.
    if ($irreversible > 0) { $out = \__mc_mb_iconv_enc8_each($enc, $u, $strict); }
    return $out === null ? null : \__mc_mb_iso2022_canon($enc, $out);
}

/**
 * One UTF-8 character (or substitute piece) through `$cd`; null when the host
 * could not spell all of it, exactly.
 * @param array<int,\Ffi\Ptr> $cells
 */
function __mc_mb_iconv_enc_one(int $cd, string $piece, array $cells, int $cap): ?string
{
    \poke_i64($cells[6], 0, 0);
    $got = \__mc_mb_iconv_feed($cd, $piece, 0, $cells, $cap);
    if (\peek_i64($cells[5], 0) !== \strlen($piece) || \peek_i64($cells[6], 0) !== 0) { return null; }
    return $got;
}

function __mc_mb_iconv_enc8_each(string $enc, string $u, bool $strict): ?string
{
    $cd = \__mc_mb_iconv_open($enc, false);
    $cap = 4096;
    $cells = \__mc_mb_iconv_cells($cap);
    $out = "";
    foreach (\__mc_mb_units($u) as $cp) {
        $got = $cp >= 0 && $cp <= 0x10FFFF ? \__mc_mb_iconv_enc_one($cd, \__mc_mb_u8_chr($cp), $cells, $cap) : null;
        if ($got === null) {
            if ($strict) {
                \__mc_mb_iconv_free($cd, $cells);
                return null;
            }
            $got = "";
            foreach (\__mc_mb_iconv_subst($cp) as $piece) {
                if ($piece === "") { break; }
                $p = \__mc_mb_iconv_enc_one($cd, $piece, $cells, $cap);
                if ($p !== null) { $got = $p; break; }
            }
        }
        $out = $out . $got;
    }
    $out = $out . \__mc_mb_iconv_feed($cd, "", 0, $cells, $cap);
    \__mc_mb_iconv_free($cd, $cells);
    return $out;
}

/**
 * Drop the redundant escapes an ISO-2022 encoder may write — musl switches back
 * to ASCII after every character — so the bytes are php's minimal form: an
 * escape is kept only when it changes the active set before the next byte.
 */
function __mc_mb_iso2022_canon(string $enc, string $s): string
{
    if (!\str_starts_with(\__mc_mb_iconv_name($enc), "ISO-2022-JP") || !\str_contains($s, "\x1b")) { return $s; }
    $n = \strlen($s);
    $out = "";
    $cur = "\x1b(B";
    $pend = "";
    $i = 0;
    while ($i < $n) {
        if ($s[$i] === "\x1b" && $i + 2 < $n) {
            $len = $s[$i + 1] === '$' && $s[$i + 2] === '(' ? 4 : 3;
            $pend = \substr($s, $i, $len);
            $i = $i + $len;
            continue;
        }
        if ($pend !== "") {
            if ($pend !== $cur) { $out = $out . $pend; $cur = $pend; }
            $pend = "";
        }
        $out = $out . $s[$i];
        $i = $i + 1;
    }
    if ($pend !== "" && $pend !== $cur) { $out = $out . $pend; }
    return $out;
}

/**
 * The host-iconv encode through `$cd`; null when `$strict` met a character it
 * cannot spell. Irreversible substitutions the host made add up in `$cells[6]`.
 * @param array<int,\Ffi\Ptr> $cells
 */
function __mc_mb_iconv_enc8_run(int $cd, array $cells, int $cap, string $u, bool $strict): ?string
{
    $n = \strlen($u);
    $out = "";
    $at = 0;
    while ($at < $n) {
        $out = $out . \__mc_mb_iconv_feed($cd, $u, $at, $cells, $cap);
        $at = \peek_i64($cells[5], 0);
        if ($at >= $n) { break; }
        if ($strict) { return null; }
        $b = \ord($u[$at]);
        $len = $b === 0xFF || $b < 0x80 ? 1 : ($b >= 0xF0 ? 4 : ($b >= 0xE0 ? 3 : 2));
        $sub = \__mc_mb_iconv_subst($b === 0xFF ? -1 : \__mc_mb_cp(0, $u, $at, $at + $len));
        foreach ($sub as $piece) {
            if ($piece === "") { break; }
            $got = \__mc_mb_iconv_feed($cd, $piece, 0, $cells, $cap);
            if (\peek_i64($cells[5], 0) === \strlen($piece)) {
                $out = $out . $got;
                break;
            }
        }
        $at = $at + $len;
    }
    return $out . \__mc_mb_iconv_feed($cd, "", 0, $cells, $cap);
}

/**
 * The substitute for `$cp` (-1 = bad input) as UTF-8 candidates to push through
 * the target's own descriptor, in preference order — a stateful target must see
 * the substitute in-stream, not spliced in afterwards.
 * @return string[]
 */
function __mc_mb_iconv_subst(int $cp): array
{
    $st = \__mc_mb_subst();
    if ($st[0] === 1) { return [""]; }
    if ($cp >= 0 && $st[0] === 2) { return ["U+" . \strtoupper(\dechex($cp))]; }
    if ($cp >= 0 && $st[0] === 3) { return ["&#x" . \strtoupper(\dechex($cp)) . ";"]; }
    $char = \__mc_mb_u8_chr($st[1]);
    return $st[0] === 0 || $cp >= 0 ? [$char, "?"] : [$char, ""];
}
