<?php
/**
 * gen_manifest.php — emit the manticore.json for one tier of the ladder.
 *
 * A tier is expressed the way the builder actually models a multi-directory
 * source set: `"composer": true`, which pulls the project's own autoload roots
 * plus every package in composer.lock (Main.php:1166 composer_source_dirs), and
 * then `exclude` to CUT the tiers above N back out. There is exactly one `src`
 * per application, so listing directories individually is not an option, and
 * two applications in one manifest would each write `<prefix>_stubs.c` and
 * clobber each other.
 *
 * The manifest is written INTO the app directory because that is where
 * composer.json / composer.lock live and where the builder looks for them.
 *
 * Everything is one whole-program application: a compiled library's `.sig`
 * carries functions only, so classes, interfaces, traits, enums and constants
 * cannot cross a library boundary.
 *
 * Usage: php tools/audit/gen_manifest.php <N> --app <dir> [--out <path>]
 */

$tier = $argv[1] ?? '';
$app = '/Users/taras/var/projects/symfony-demo-probe/app';
$out = '';
for ($i = 2; $i < count($argv); $i++) {
    if ($argv[$i] === '--app' && isset($argv[$i + 1])) { $app = $argv[++$i]; }
    elseif ($argv[$i] === '--out' && isset($argv[$i + 1])) { $out = $argv[++$i]; }
}
if ($tier === '') {
    fwrite(STDERR, "gen_manifest: usage: gen_manifest.php <N> --app <dir>\n");
    exit(2);
}
$tierKey = str_starts_with($tier, 'T') ? $tier : 'T' . $tier;
if ($out === '') { $out = $app . '/manticore.' . strtolower($tierKey) . '.json'; }

$j = json_decode((string)@file_get_contents('docs/audit/tiers.json'), true);
if (!isset($j['tiers'][$tierKey])) {
    fwrite(STDERR, "gen_manifest: unknown tier $tierKey — run gen_tiers.php first\n");
    exit(2);
}

$below = [];
$exclude = [];
$seenTier = false;
foreach ($j['tiers'] as $name => $info) {
    if ($seenTier) {
        // A tier ABOVE the one under test: cut every one of its packages out of
        // the composer-derived source set.
        foreach ($info['dirs'] as $d) { $exclude['./' . $d] = true; }
        continue;
    }
    foreach ($info['packages'] as $p) { $below[] = $p; }
    foreach ($info['exclude'] as $e) { $exclude[$e] = true; }
    if ($name === $tierKey) { $seenTier = true; }
}

// The application's own code is T8. Below that, exclude it too, or every tier
// would drag in the whole app and stop being a tier.
if ($tierKey !== 'T8') {
    foreach (['./src', './config', './templates', './tests', './migrations'] as $d) {
        $exclude[$d] = true;
    }
}

// A smoke entry that merely NAMES the tier is not enough: with nothing
// reachable the whole tier is dead-code-eliminated, the stub list comes back
// empty, and the tier reads as complete. Touching each package's classes
// through class_exists keeps their metadata live without needing a constructor
// that works.
@mkdir($app . '/tiers', 0777, true);
$entryRel = 'tiers/' . strtolower($tierKey) . '_smoke.php';

$lines = [
    '<?php', '',
    '// GENERATED by tools/audit/gen_manifest.php — do not edit.',
    '// Keeps every package of tiers <= ' . $tierKey . ' reachable, so dead-code',
    '// elimination cannot empty the stub list and make the tier look complete.',
    '',
    '$live = 0;',
];
foreach ($below as $p) {
    // vendor/<vendor>/<pkg> -> a plausible root namespace. Wrong guesses are
    // harmless: class_exists on an unknown name is simply false, and the point
    // is to keep the compiler from discarding the compiled sources.
    $parts = explode('/', $p);
    $ns = str_replace(['-', '_'], '', ucwords($parts[0], '-_'))
        . '\\' . str_replace(['-', '_'], '', ucwords($parts[1] ?? '', '-_'));
    $lines[] = '$live += (int)class_exists(' . var_export($ns, true) . ');';
}
$lines[] = 'echo "tier ' . $tierKey . ': ", $live, " root classes live\n";';
file_put_contents($app . '/' . $entryRel, implode("\n", $lines) . "\n");

$manifest = [
    'applications' => [[
        'name' => 'audit_' . strtolower($tierKey),
        'src' => 'tiers',
        'output' => 'audit-' . strtolower($tierKey) . '_bin',
        'entry' => $entryRel,
        'composer' => true,
        'extensions' => [],
        'exclude' => array_keys($exclude),
    ]],
];

file_put_contents($out, json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
printf("gen_manifest: %s -> %s (%d packages in scope, %d excludes)\n",
    $tierKey, $out, count($below), count($exclude));
