<?php
/**
 * rank.php — join the evidence with the annotations, score, render GAPS.md.
 *
 * GAPS.md is generated, never hand-edited: `--check` regenerates into a buffer
 * and fails on any difference, which is what guarantees no finding was quietly
 * typed in without evidence behind it.
 *
 * Score, highest first:
 *
 *     (4 - class) * 1000        severity dominates. An S0 outranks every S1,
 *                               because a silent wrong answer poisons the
 *                               measurements that would find anything else.
 *   + (9 - tier)  * 50          blast radius: a tier-1 gap blocks tiers 1..8.
 *   + depth_weight * 10         a compiler root that collapses several rows
 *                               beats the rows it collapses.
 *   + packages                  tie-break by how much code is affected.
 *
 * Usage: php tools/audit/rank.php [--check]
 */

$check = in_array('--check', $argv, true);

$depthWeight = ['compiler-root' => 5, 'repr' => 4, 'parser' => 3, 'prelude' => 2, 'stdlib-leaf' => 1];
$classNum = ['S0' => 0, 'S1' => 1, 'S2' => 2, 'S3' => 3, 'S4' => 4];

$rows = [];
foreach (file('docs/audit/findings.tsv') as $line) {
    $line = rtrim($line, "\n");
    if ($line === '' || $line[0] === '#') { continue; }
    $p = explode("\t", $line);
    if (count($p) < 8) { continue; }
    [$id, $class, $tier, $depth, $packages, $epic, $evidence, $title] = $p;
    $rows[] = [
        'id' => $id, 'class' => $class, 'tier' => (int)$tier, 'depth' => $depth,
        'packages' => (int)$packages, 'epic' => $epic, 'evidence' => $evidence,
        'title' => $title,
        'score' => (4 - ($classNum[$class] ?? 4)) * 1000
                 + (9 - (int)$tier) * 50
                 + ($depthWeight[$depth] ?? 0) * 10
                 + (int)$packages,
    ];
}
usort($rows, function ($a, $b) {
    return $b['score'] <=> $a['score'] ?: strcmp($a['id'], $b['id']);
});

$byEpic = [];
foreach ($rows as $r) { $byEpic[$r['epic']][] = $r; }
uasort($byEpic, function ($a, $b) { return $b[0]['score'] <=> $a[0]['score']; });

$capStatus = [];
foreach (@file('docs/audit/data/capability.tsv') ?: [] as $i => $line) {
    if ($i === 0) { continue; }
    $p = explode("\t", rtrim($line, "\n"));
    if (count($p) >= 3) { $capStatus[$p[2]] = ($capStatus[$p[2]] ?? 0) + 1; }
}

$md = "# GAPS — symfony-demo audit\n\n";
$md .= "**GENERATED by `tools/audit/rank.php`. Do not edit.**\n";
$md .= "Evidence is under `docs/audit/data/` and `docs/audit/probes/`; the severity,\n";
$md .= "depth and ownership calls are in `docs/audit/findings.tsv`. `rank.php --check`\n";
$md .= "regenerates this file and fails on any difference, so nothing here is a claim\n";
$md .= "without a file behind it.\n\n";

$md .= "## Severity classes\n\n";
$md .= "| class | meaning |\n|---|---|\n";
$md .= "| S0 | **silent wrong answer** — compiles, links, runs, answers differently than php. Ranked above everything because it poisons every other measurement: a green build is actively misleading. |\n";
$md .= "| S1 | runtime hard failure — crash, uncaught throw, or a `return 0` link-stub that explodes later |\n";
$md .= "| S2 | compile or link hard failure, or a compiler crash |\n";
$md .= "| S3 | static finding with no observed runtime effect |\n";
$md .= "| S4 | advisory / analyzer residue |\n\n";

$counts = [];
foreach ($rows as $r) { $counts[$r['class']] = ($counts[$r['class']] ?? 0) + 1; }
ksort($counts);
$md .= "**" . count($rows) . " findings**: ";
$parts = [];
foreach ($counts as $c => $n) { $parts[] = "$n $c"; }
$md .= implode(', ', $parts) . ".\n\n";
if ($capStatus) {
    ksort($capStatus);
    $cp = [];
    foreach ($capStatus as $s => $n) { $cp[] = "$n $s"; }
    $md .= "Capability probes: " . implode(', ', $cp) . " (`docs/audit/data/capability.tsv`).\n\n";
}

$md .= "## Ranked\n\n";
$md .= "| # | class | id | tier | depth | title | evidence |\n";
$md .= "|---|---|---|---|---|---|---|\n";
foreach ($rows as $i => $r) {
    $md .= sprintf("| %d | %s | `%s` | T%d | %s | %s | [`%s`](%s) |\n",
        $i + 1, $r['class'], $r['id'], $r['tier'], $r['depth'], $r['title'],
        $r['evidence'], $r['evidence']);
}

$md .= "\n## By owning epic\n\n";
$md .= "The ladder tier is the implementation order: a tier's dependency closure\n";
$md .= "lies entirely in lower tiers, so a gap first seen at tier N blocks tiers\n";
$md .= "N..8 and nothing below.\n\n";
foreach ($byEpic as $epic => $rs) {
    $lowest = 9;
    foreach ($rs as $r) { $lowest = min($lowest, $r['tier']); }
    $md .= "### `$epic` — " . count($rs) . " finding(s), first bites at T$lowest\n\n";
    foreach ($rs as $r) { $md .= "- **{$r['class']}** `{$r['id']}` — {$r['title']}\n"; }
    $md .= "\n";
}

$out = 'docs/audit/GAPS.md';
if ($check) {
    $cur = (string)@file_get_contents($out);
    if (rtrim($cur) !== rtrim($md)) {
        fwrite(STDERR, "rank: GAPS.md is out of date or was hand-edited — regenerate with `php tools/audit/rank.php`\n");
        exit(1);
    }
    echo "rank: GAPS.md matches its inputs\n";
    exit(0);
}
file_put_contents($out, $md);
printf("rank: %d findings -> %s\n", count($rows), $out);
