<?php

/**
 * ext/tokenizer, scanner core.
 *
 * ⚠ THIS FILE NAMES NOTHING ZEND OWNS, ON PURPOSE. It can be `require`d under
 * plain `php`, which is what makes the differential harness possible: run
 * __McTok and Zend's C tokenizer inside the SAME interpreter and diff. A
 * divergence there is an ALGORITHM bug; a divergence that only shows up in the
 * compiled binary is a COMPILER bug. Keeping those two apart is worth more than
 * any single optimisation here, so do not move `PhpToken` / `token_get_all` /
 * `token_name` into this file — they live in prelude/tokenizer_api.php.
 *
 * Byte reads are spelled `ord($s[$i])`, never `$c = $s[$i]`. Both work under
 * Zend, but only the first is rewritten UNCONDITIONALLY by
 * {@see \Compile\Mir\Passes\DemoteCharLocals} (its `rewriteOrd`) to the
 * allocation-free `__str_byte_at`. The char-local form needs a whole-function
 * proof, and one concat or argument use silently turns every byte read back
 * into a malloc — a 100 MB regression with no error. Never introduce one.
 *
 * The scanner fills four PARALLEL PACKED arrays. The heterogeneous
 * `array{int,string,int}|string` shape ext/tokenizer is specified in terms of is
 * built exactly once, at the API boundary, in the other file — never in here,
 * never per token.
 */

// ---8<--- GENERATED by tools/gen_tokenizer_tables.php — do not edit ---8<---
// php 8.5.8. Regenerate with: php tools/gen_tokenizer_tables.php

/** T_* ids as class constants — see the note in the generator. */
final class __McTokId
{
    public const T_LNUMBER = 260;
    public const T_DNUMBER = 261;
    public const T_STRING = 262;
    public const T_NAME_FULLY_QUALIFIED = 263;
    public const T_NAME_RELATIVE = 264;
    public const T_NAME_QUALIFIED = 265;
    public const T_VARIABLE = 266;
    public const T_INLINE_HTML = 267;
    public const T_ENCAPSED_AND_WHITESPACE = 268;
    public const T_CONSTANT_ENCAPSED_STRING = 269;
    public const T_STRING_VARNAME = 270;
    public const T_NUM_STRING = 271;
    public const T_INCLUDE = 272;
    public const T_INCLUDE_ONCE = 273;
    public const T_EVAL = 274;
    public const T_REQUIRE = 275;
    public const T_REQUIRE_ONCE = 276;
    public const T_LOGICAL_OR = 277;
    public const T_LOGICAL_XOR = 278;
    public const T_LOGICAL_AND = 279;
    public const T_PRINT = 280;
    public const T_YIELD = 281;
    public const T_YIELD_FROM = 282;
    public const T_INSTANCEOF = 283;
    public const T_NEW = 284;
    public const T_CLONE = 285;
    public const T_EXIT = 286;
    public const T_IF = 287;
    public const T_ELSEIF = 288;
    public const T_ELSE = 289;
    public const T_ENDIF = 290;
    public const T_ECHO = 291;
    public const T_DO = 292;
    public const T_WHILE = 293;
    public const T_ENDWHILE = 294;
    public const T_FOR = 295;
    public const T_ENDFOR = 296;
    public const T_FOREACH = 297;
    public const T_ENDFOREACH = 298;
    public const T_DECLARE = 299;
    public const T_ENDDECLARE = 300;
    public const T_AS = 301;
    public const T_SWITCH = 302;
    public const T_ENDSWITCH = 303;
    public const T_CASE = 304;
    public const T_DEFAULT = 305;
    public const T_MATCH = 306;
    public const T_BREAK = 307;
    public const T_CONTINUE = 308;
    public const T_GOTO = 309;
    public const T_FUNCTION = 310;
    public const T_FN = 311;
    public const T_CONST = 312;
    public const T_RETURN = 313;
    public const T_TRY = 314;
    public const T_CATCH = 315;
    public const T_FINALLY = 316;
    public const T_THROW = 317;
    public const T_USE = 318;
    public const T_INSTEADOF = 319;
    public const T_GLOBAL = 320;
    public const T_STATIC = 321;
    public const T_ABSTRACT = 322;
    public const T_FINAL = 323;
    public const T_PRIVATE = 324;
    public const T_PROTECTED = 325;
    public const T_PUBLIC = 326;
    public const T_PRIVATE_SET = 327;
    public const T_PROTECTED_SET = 328;
    public const T_PUBLIC_SET = 329;
    public const T_READONLY = 330;
    public const T_VAR = 331;
    public const T_UNSET = 332;
    public const T_ISSET = 333;
    public const T_EMPTY = 334;
    public const T_HALT_COMPILER = 335;
    public const T_CLASS = 336;
    public const T_TRAIT = 337;
    public const T_INTERFACE = 338;
    public const T_ENUM = 339;
    public const T_EXTENDS = 340;
    public const T_IMPLEMENTS = 341;
    public const T_NAMESPACE = 342;
    public const T_LIST = 343;
    public const T_ARRAY = 344;
    public const T_CALLABLE = 345;
    public const T_LINE = 346;
    public const T_FILE = 347;
    public const T_DIR = 348;
    public const T_CLASS_C = 349;
    public const T_TRAIT_C = 350;
    public const T_METHOD_C = 351;
    public const T_FUNC_C = 352;
    public const T_PROPERTY_C = 353;
    public const T_NS_C = 354;
    public const T_ATTRIBUTE = 355;
    public const T_PLUS_EQUAL = 356;
    public const T_MINUS_EQUAL = 357;
    public const T_MUL_EQUAL = 358;
    public const T_DIV_EQUAL = 359;
    public const T_CONCAT_EQUAL = 360;
    public const T_MOD_EQUAL = 361;
    public const T_AND_EQUAL = 362;
    public const T_OR_EQUAL = 363;
    public const T_XOR_EQUAL = 364;
    public const T_SL_EQUAL = 365;
    public const T_SR_EQUAL = 366;
    public const T_COALESCE_EQUAL = 367;
    public const T_BOOLEAN_OR = 368;
    public const T_BOOLEAN_AND = 369;
    public const T_IS_EQUAL = 370;
    public const T_IS_NOT_EQUAL = 371;
    public const T_IS_IDENTICAL = 372;
    public const T_IS_NOT_IDENTICAL = 373;
    public const T_IS_SMALLER_OR_EQUAL = 374;
    public const T_IS_GREATER_OR_EQUAL = 375;
    public const T_SPACESHIP = 376;
    public const T_SL = 377;
    public const T_SR = 378;
    public const T_INC = 379;
    public const T_DEC = 380;
    public const T_INT_CAST = 381;
    public const T_DOUBLE_CAST = 382;
    public const T_STRING_CAST = 383;
    public const T_ARRAY_CAST = 384;
    public const T_OBJECT_CAST = 385;
    public const T_BOOL_CAST = 386;
    public const T_UNSET_CAST = 387;
    public const T_VOID_CAST = 388;
    public const T_OBJECT_OPERATOR = 389;
    public const T_NULLSAFE_OBJECT_OPERATOR = 390;
    public const T_DOUBLE_ARROW = 391;
    public const T_COMMENT = 392;
    public const T_DOC_COMMENT = 393;
    public const T_OPEN_TAG = 394;
    public const T_OPEN_TAG_WITH_ECHO = 395;
    public const T_CLOSE_TAG = 396;
    public const T_WHITESPACE = 397;
    public const T_START_HEREDOC = 398;
    public const T_END_HEREDOC = 399;
    public const T_DOLLAR_OPEN_CURLY_BRACES = 400;
    public const T_CURLY_OPEN = 401;
    public const T_DOUBLE_COLON = 402;
    public const T_NS_SEPARATOR = 403;
    public const T_ELLIPSIS = 404;
    public const T_COALESCE = 405;
    public const T_POW = 406;
    public const T_POW_EQUAL = 407;
    public const T_PIPE = 408;
    public const T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG = 409;
    public const T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG = 410;
    public const T_BAD_CHARACTER = 411;
}

/** T_* id -> name, for token_name(). @return array<int,string> */
function __mc_tok_names(): array
{
    return [
        260 => 'T_LNUMBER',
        261 => 'T_DNUMBER',
        262 => 'T_STRING',
        263 => 'T_NAME_FULLY_QUALIFIED',
        264 => 'T_NAME_RELATIVE',
        265 => 'T_NAME_QUALIFIED',
        266 => 'T_VARIABLE',
        267 => 'T_INLINE_HTML',
        268 => 'T_ENCAPSED_AND_WHITESPACE',
        269 => 'T_CONSTANT_ENCAPSED_STRING',
        270 => 'T_STRING_VARNAME',
        271 => 'T_NUM_STRING',
        272 => 'T_INCLUDE',
        273 => 'T_INCLUDE_ONCE',
        274 => 'T_EVAL',
        275 => 'T_REQUIRE',
        276 => 'T_REQUIRE_ONCE',
        277 => 'T_LOGICAL_OR',
        278 => 'T_LOGICAL_XOR',
        279 => 'T_LOGICAL_AND',
        280 => 'T_PRINT',
        281 => 'T_YIELD',
        282 => 'T_YIELD_FROM',
        283 => 'T_INSTANCEOF',
        284 => 'T_NEW',
        285 => 'T_CLONE',
        286 => 'T_EXIT',
        287 => 'T_IF',
        288 => 'T_ELSEIF',
        289 => 'T_ELSE',
        290 => 'T_ENDIF',
        291 => 'T_ECHO',
        292 => 'T_DO',
        293 => 'T_WHILE',
        294 => 'T_ENDWHILE',
        295 => 'T_FOR',
        296 => 'T_ENDFOR',
        297 => 'T_FOREACH',
        298 => 'T_ENDFOREACH',
        299 => 'T_DECLARE',
        300 => 'T_ENDDECLARE',
        301 => 'T_AS',
        302 => 'T_SWITCH',
        303 => 'T_ENDSWITCH',
        304 => 'T_CASE',
        305 => 'T_DEFAULT',
        306 => 'T_MATCH',
        307 => 'T_BREAK',
        308 => 'T_CONTINUE',
        309 => 'T_GOTO',
        310 => 'T_FUNCTION',
        311 => 'T_FN',
        312 => 'T_CONST',
        313 => 'T_RETURN',
        314 => 'T_TRY',
        315 => 'T_CATCH',
        316 => 'T_FINALLY',
        317 => 'T_THROW',
        318 => 'T_USE',
        319 => 'T_INSTEADOF',
        320 => 'T_GLOBAL',
        321 => 'T_STATIC',
        322 => 'T_ABSTRACT',
        323 => 'T_FINAL',
        324 => 'T_PRIVATE',
        325 => 'T_PROTECTED',
        326 => 'T_PUBLIC',
        327 => 'T_PRIVATE_SET',
        328 => 'T_PROTECTED_SET',
        329 => 'T_PUBLIC_SET',
        330 => 'T_READONLY',
        331 => 'T_VAR',
        332 => 'T_UNSET',
        333 => 'T_ISSET',
        334 => 'T_EMPTY',
        335 => 'T_HALT_COMPILER',
        336 => 'T_CLASS',
        337 => 'T_TRAIT',
        338 => 'T_INTERFACE',
        339 => 'T_ENUM',
        340 => 'T_EXTENDS',
        341 => 'T_IMPLEMENTS',
        342 => 'T_NAMESPACE',
        343 => 'T_LIST',
        344 => 'T_ARRAY',
        345 => 'T_CALLABLE',
        346 => 'T_LINE',
        347 => 'T_FILE',
        348 => 'T_DIR',
        349 => 'T_CLASS_C',
        350 => 'T_TRAIT_C',
        351 => 'T_METHOD_C',
        352 => 'T_FUNC_C',
        353 => 'T_PROPERTY_C',
        354 => 'T_NS_C',
        355 => 'T_ATTRIBUTE',
        356 => 'T_PLUS_EQUAL',
        357 => 'T_MINUS_EQUAL',
        358 => 'T_MUL_EQUAL',
        359 => 'T_DIV_EQUAL',
        360 => 'T_CONCAT_EQUAL',
        361 => 'T_MOD_EQUAL',
        362 => 'T_AND_EQUAL',
        363 => 'T_OR_EQUAL',
        364 => 'T_XOR_EQUAL',
        365 => 'T_SL_EQUAL',
        366 => 'T_SR_EQUAL',
        367 => 'T_COALESCE_EQUAL',
        368 => 'T_BOOLEAN_OR',
        369 => 'T_BOOLEAN_AND',
        370 => 'T_IS_EQUAL',
        371 => 'T_IS_NOT_EQUAL',
        372 => 'T_IS_IDENTICAL',
        373 => 'T_IS_NOT_IDENTICAL',
        374 => 'T_IS_SMALLER_OR_EQUAL',
        375 => 'T_IS_GREATER_OR_EQUAL',
        376 => 'T_SPACESHIP',
        377 => 'T_SL',
        378 => 'T_SR',
        379 => 'T_INC',
        380 => 'T_DEC',
        381 => 'T_INT_CAST',
        382 => 'T_DOUBLE_CAST',
        383 => 'T_STRING_CAST',
        384 => 'T_ARRAY_CAST',
        385 => 'T_OBJECT_CAST',
        386 => 'T_BOOL_CAST',
        387 => 'T_UNSET_CAST',
        388 => 'T_VOID_CAST',
        389 => 'T_OBJECT_OPERATOR',
        390 => 'T_NULLSAFE_OBJECT_OPERATOR',
        391 => 'T_DOUBLE_ARROW',
        392 => 'T_COMMENT',
        393 => 'T_DOC_COMMENT',
        394 => 'T_OPEN_TAG',
        395 => 'T_OPEN_TAG_WITH_ECHO',
        396 => 'T_CLOSE_TAG',
        397 => 'T_WHITESPACE',
        398 => 'T_START_HEREDOC',
        399 => 'T_END_HEREDOC',
        400 => 'T_DOLLAR_OPEN_CURLY_BRACES',
        401 => 'T_CURLY_OPEN',
        402 => 'T_DOUBLE_COLON',
        403 => 'T_NS_SEPARATOR',
        404 => 'T_ELLIPSIS',
        405 => 'T_COALESCE',
        406 => 'T_POW',
        407 => 'T_POW_EQUAL',
        408 => 'T_PIPE',
        409 => 'T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG',
        410 => 'T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG',
        411 => 'T_BAD_CHARACTER',
    ];
}

/** lowercase keyword -> T_* id. @return array<string,int> */
function __mc_tok_keywords(): array
{
    return [
        'abstract' => 322,
        'and' => 279,
        'array' => 344,
        'as' => 301,
        'break' => 307,
        'callable' => 345,
        'case' => 304,
        'catch' => 315,
        'class' => 336,
        'clone' => 285,
        'const' => 312,
        'continue' => 308,
        'declare' => 299,
        'default' => 305,
        'die' => 286,
        'do' => 292,
        'echo' => 291,
        'else' => 289,
        'elseif' => 288,
        'empty' => 334,
        'enddeclare' => 300,
        'endfor' => 296,
        'endforeach' => 298,
        'endif' => 290,
        'endswitch' => 303,
        'endwhile' => 294,
        'enum' => 262,
        'eval' => 274,
        'exit' => 286,
        'extends' => 340,
        'final' => 323,
        'finally' => 316,
        'fn' => 311,
        'for' => 295,
        'foreach' => 297,
        'function' => 310,
        'global' => 320,
        'goto' => 309,
        'if' => 287,
        'implements' => 341,
        'include' => 272,
        'include_once' => 273,
        'instanceof' => 283,
        'insteadof' => 319,
        'interface' => 338,
        'isset' => 333,
        'list' => 343,
        'match' => 306,
        'namespace' => 342,
        'new' => 284,
        'or' => 277,
        'print' => 280,
        'private' => 324,
        'protected' => 325,
        'public' => 326,
        'readonly' => 330,
        'require' => 275,
        'require_once' => 276,
        'return' => 313,
        'static' => 321,
        'switch' => 302,
        'throw' => 317,
        'trait' => 337,
        'try' => 314,
        'unset' => 332,
        'use' => 318,
        'var' => 331,
        'while' => 293,
        'xor' => 278,
        'yield' => 281,
        '__halt_compiler' => 335,
    ];
}

/** lowercase magic constant -> T_* id. @return array<string,int> */
function __mc_tok_magic(): array
{
    return [
        '__line__' => 346,
        '__file__' => 347,
        '__dir__' => 348,
        '__function__' => 352,
        '__class__' => 349,
        '__trait__' => 350,
        '__method__' => 351,
        '__namespace__' => 354,
        '__property__' => 353,
    ];
}

/** lowercase cast word (no parens) -> T_* id. @return array<string,int> */
function __mc_tok_casts(): array
{
    return [
        'int' => 381,
        'integer' => 381,
        'bool' => 386,
        'boolean' => 386,
        'float' => 382,
        'double' => 382,
        'real' => 382,
        'string' => 383,
        'array' => 384,
        'object' => 385,
        'unset' => 387,
        'void' => 388,
    ];
}

/** multi-byte operator -> T_* id; single bytes stay bare strings.
 *  @return array<string,int> */
function __mc_tok_operators(): array
{
    return [
        '===' => 372,
        '!==' => 373,
        '==' => 370,
        '!=' => 371,
        '<>' => 371,
        '<=>' => 376,
        '<=' => 374,
        '>=' => 375,
        '&&' => 369,
        '||' => 368,
        '??' => 405,
        '??=' => 367,
        '++' => 379,
        '--' => 380,
        '+=' => 356,
        '-=' => 357,
        '*=' => 358,
        '/=' => 359,
        '.=' => 360,
        '%=' => 361,
        '**=' => 407,
        '**' => 406,
        '&=' => 362,
        '|=' => 363,
        '^=' => 364,
        '<<=' => 365,
        '>>=' => 366,
        '<<' => 377,
        '>>' => 378,
        '=>' => 391,
        '->' => 389,
        '?->' => 390,
        '::' => 402,
        '...' => 404,
        '#[' => 355,
        '|>' => 408,
    ];
}

/** php 8.4 asymmetric visibility: ONE token despite the parens. */
function __mc_tok_paren_keywords(): array
{
    return [
        'public(set)' => 329,
        'protected(set)' => 328,
        'private(set)' => 327,
    ];
}

/** `yield from` is ONE token whose text spans the inner whitespace. */
function __mc_tok_yield_from(): int { return 282; }

/** `enum` is CONTEXTUAL — this id only when whitespace + an identifier
 *  follows; otherwise the keyword table's T_STRING id stands. */
function __mc_tok_enum(): int { return 339; }

/** `&` is decided by LOOKAHEAD past whitespace: a variable or `...` next. */
function __mc_tok_amp_followed(): int { return 409; }
function __mc_tok_amp_plain(): int { return 410; }

// ---8<--- END GENERATED ---8<---

final class __McTok
{
    // Lexer states, mirroring Zend's ST_*. A stack, because interpolation nests.
    public const ST_HTML = 0;
    public const ST_PHP = 1;
    public const ST_DQ = 2;
    public const ST_BT = 3;
    public const ST_HEREDOC = 4;
    public const ST_NOWDOC = 5;
    public const ST_VARNAME = 6;
    public const ST_OFFSET = 7;

    // Character classes, indexed by byte through self::CLS.
    public const K_OTHER = 0;
    public const K_WS = 1;
    public const K_ID = 2;
    public const K_DIGIT = 3;
    public const K_QUOTE = 4;
    public const K_PUNCT = 5;

    /**
     * 256 entries, one ASCII DIGIT each, so the lookup is
     * `ord(self::CLS[$b]) - 48` — a byte read from a folded literal, no array
     * bounds check and no hashing. Digits rather than `\x` escapes so the table
     * stays readable and identical under both interpreters.
     *
     * Bytes >= 0x80 are identifier characters in PHP 8. `'`, `"` and backtick
     * are quotes. Control bytes other than \t \n \r, plus 0x7f, are class 0 —
     * T_BAD_CHARACTER candidates.
     */
    public const CLS =
          '0000000001100100' . '0000000000000000'
        . '1545555455555555' . '3333333333555555'
        . '5222222222222222' . '2222222222255552'
        . '4222222222222222' . '2222222222255550'
        . '2222222222222222' . '2222222222222222'
        . '2222222222222222' . '2222222222222222'
        . '2222222222222222' . '2222222222222222'
        . '2222222222222222' . '2222222222222222';

    /**
     * id AND line in ONE packed word: `$id | ($line << 12)`. Every T_* id and
     * every single-byte id is < 4096, so 12 bits hold it and the line takes the
     * rest.
     *
     * The four parallel appends were 41% of the scan — not because an append is
     * slow (4.6 ns, half of Zend·s) but because there were FOUR of them per
     * token. Packing removes one, and $offs is only filled when PhpToken asks
     * for it, which removes another on the token_get_all path.
     * @var int[]
     */
    public array $meta = [];
    /** @var string[] */
    public array $texts = [];
    /** @var int[] */
    public array $offs = [];
    public int $n = 0;
    /** Fill $offs? Only PhpToken::$pos needs it. */
    public int $wantPos = 0;

    /** @var array<string,int> */
    private array $kw = [];
    /** @var array<string,int> */
    private array $magic = [];
    /** @var array<string,int> */
    private array $casts = [];
    /** @var array<string,int> */
    private array $ops = [];
    /** @var array<string,int> */
    private array $parenKw = [];
    /** 256 flags: can this byte begin a multi-byte operator? Built in ctor. */
    private string $opLead = '';
    /**
     * The 256 one-character strings, built once. A single-byte token — `;` `(`
     * `)` `,` and a lone space — is the most frequent token class there is, and
     * substr() mints a fresh headered buffer for each one. Handing back the
     * interned string instead removes an ALLOCATION from the hottest path.
     * @var string[]
     */
    private array $chr = [];

    /** @var int[] */
    private array $stStack = [];
    /** @var string[] */
    private array $hdLabel = [];

    private int $st = 0;
    private int $line = 1;
    private int $flags = 0;

    /**
     * One-shots that survive whitespace and comments but nothing else — see
     * push(), which is the single place they are set and cleared.
     *
     * afterArrow: a reserved word after `->` / `?->` is a property name, so it
     * is T_STRING with NO flag involved. afterDoubleColon / afterFunction: the
     * two MEASURED contexts where TOKEN_PARSE downgrades a reserved word —
     * `Foo::class`, `Foo::list`, and a method named `function list()`.
     */
    private int $afterArrow = 0;
    private int $afterDoubleColon = 0;
    private int $afterFunction = 0;
    /** `__halt_compiler` seen; the tail after its `;` is one T_INLINE_HTML. */
    private int $halt = 0;
    /** Brace depth of a `{$ ... }` interpolation, -1 when not inside one. */
    private int $curlyDepth = -1;

    public function __construct()
    {
        $this->kw = __mc_tok_keywords();
        $this->magic = __mc_tok_magic();
        $this->casts = __mc_tok_casts();
        $this->ops = __mc_tok_operators();
        $this->parenKw = __mc_tok_paren_keywords();

        // Which bytes can BEGIN a multi-byte operator, DERIVED from the operator
        // table so the two cannot drift apart.
        //
        // Without this, every `;` `(` `)` `,` `{` `}` — the most frequent tokens
        // in any source — paid two substr() allocations and two failed hash
        // probes before falling through to the single-byte path. None of those
        // bytes starts an operator, so the whole probe is skipped on one byte
        // read.
        $lead = [];
        foreach ($this->ops as $op => $_ignored) { $lead[\ord($op[0])] = 1; }
        $tbl = '';
        $b = 0;
        while ($b < 256) {
            $tbl = $tbl . (isset($lead[$b]) ? '1' : '0');
            $b = $b + 1;
        }
        $this->opLead = $tbl;

        $b = 0;
        while ($b < 256) { $this->chr[] = \chr($b); $b = $b + 1; }
    }

    /** Convenience entry for the differential harness. */
    public static function run(string $src, int $flags = 0, int $wantPos = 0): __McTok
    {
        $t = new __McTok();
        $t->wantPos = $wantPos;
        $t->scan($src, $flags);
        return $t;
    }

    private function push(int $id, string $text, int $line, int $off): void
    {
        $this->meta[] = $id | ($line << 12);
        $this->texts[] = $text;
        if ($this->wantPos !== 0) { $this->offs[] = $off; }
        $this->n = $this->n + 1;

        // The one-shots live here so they are set and cleared in ONE place.
        // Trivia does not disturb them: `function /*c*/ list()` still reads as a
        // method name.
        if ($id === __McTokId::T_WHITESPACE || $id === __McTokId::T_COMMENT
            || $id === __McTokId::T_DOC_COMMENT) {
            return;
        }
        $this->afterArrow = ($id === __McTokId::T_OBJECT_OPERATOR
            || $id === __McTokId::T_NULLSAFE_OBJECT_OPERATOR) ? 1 : 0;
        $this->afterDoubleColon = $id === __McTokId::T_DOUBLE_COLON ? 1 : 0;
        $this->afterFunction = $id === __McTokId::T_FUNCTION ? 1 : 0;
        if ($id === __McTokId::T_HALT_COMPILER) { $this->halt = 1; }
    }

    /** Newlines in $s[$from..$to). Walks bytes so the read demotes. */
    private function nl(string $s, int $from, int $to): int
    {
        $c = 0;
        $j = $from;
        while ($j < $to) {
            if (\ord($s[$j]) === 10) { $c = $c + 1; }
            $j = $j + 1;
        }
        return $c;
    }

    private function cls(int $b): int
    {
        return \ord(self::CLS[$b]) - 48;
    }

    public function scan(string $s, int $flags = 0): void
    {
        $this->flags = $flags;
        $len = \strlen($s);
        $i = 0;
        $this->st = self::ST_HTML;
        while ($i < $len) {
            $st = $this->st;
            if ($st === self::ST_HTML) { $i = $this->scanHtml($s, $len, $i); continue; }
            if ($st === self::ST_PHP) { $i = $this->scanPhp($s, $len, $i); continue; }
            if ($st === self::ST_OFFSET) { $i = $this->scanOffset($s, $len, $i); continue; }
            if ($st === self::ST_VARNAME) { $i = $this->scanVarname($s, $len, $i); continue; }
            $i = $this->scanEncaps($s, $len, $i);
        }
    }

    /**
     * Outside `<?php`. Everything up to the next open tag is ONE T_INLINE_HTML.
     * `<?` alone is NOT a tag with short_open_tag off (php's default) — it stays
     * inline HTML, which is why the check is for `<?php` / `<?=` only.
     */
    private function scanHtml(string $s, int $len, int $i): int
    {
        $start = $i;
        $j = $i;
        $tagAt = -1;
        while ($j < $len) {
            if (\ord($s[$j]) === 60 && $j + 1 < $len && \ord($s[$j + 1]) === 63) {
                if ($this->openTagLen($s, $len, $j) > 0) { $tagAt = $j; break; }
            }
            $j = $j + 1;
        }
        $end = $tagAt < 0 ? $len : $tagAt;
        if ($end > $start) {
            $text = \substr($s, $start, $end - $start);
            $this->push(__McTokId::T_INLINE_HTML, $text, $this->line, $start);
            $this->line = $this->line + $this->nl($s, $start, $end);
        }
        if ($tagAt < 0) { return $len; }

        $tl = $this->openTagLen($s, $len, $tagAt);
        $text = \substr($s, $tagAt, $tl);
        $id = $tl === 3 ? __McTokId::T_OPEN_TAG_WITH_ECHO : __McTokId::T_OPEN_TAG;
        $this->push($id, $text, $this->line, $tagAt);
        $this->line = $this->line + $this->nl($s, $tagAt, $tagAt + $tl);
        $this->st = self::ST_PHP;
        return $tagAt + $tl;
    }

    /**
     * Length of the open tag at $i, or 0. `<?php` must be followed by whitespace
     * or EOF, and ONE whitespace byte joins the token's text (`"<?php "`).
     */
    private function openTagLen(string $s, int $len, int $i): int
    {
        if ($i + 1 >= $len || \ord($s[$i]) !== 60 || \ord($s[$i + 1]) !== 63) { return 0; }
        if ($i + 2 < $len && \ord($s[$i + 2]) === 61) { return 3; }
        if ($i + 4 >= $len) { return 0; }
        if (\strtolower(\substr($s, $i + 2, 3)) !== 'php') { return 0; }
        $after = $i + 5;
        if ($after >= $len) { return 5; }
        $w = \ord($s[$after]);
        if ($w === 32 || $w === 9 || $w === 10) { return 6; }
        if ($w === 13) { return $after + 1 < $len && \ord($s[$after + 1]) === 10 ? 7 : 6; }
        return 0;
    }

    /** The main loop: inside `<?php`. */
    private function scanPhp(string $s, int $len, int $i): int
    {
        $b = \ord($s[$i]);
        $k = $this->cls($b);
        $line = $this->line;

        if ($k === self::K_WS) {
            $j = $i + 1;
            while ($j < $len) {
                $w = \ord($s[$j]);
                if ($w !== 32 && $w !== 9 && $w !== 10 && $w !== 13) { break; }
                $j = $j + 1;
            }
            $this->push(__McTokId::T_WHITESPACE,
                $j - $i === 1 ? $this->chr[$b] : \substr($s, $i, $j - $i), $line, $i);
            $this->line = $line + $this->nl($s, $i, $j);
            return $j;
        }

        if ($k === self::K_ID) { return $this->scanIdent($s, $len, $i, $line); }
        if ($k === self::K_DIGIT) { return $this->scanNumber($s, $len, $i, $line); }

        // `$var`
        if ($b === 36 && $i + 1 < $len && $this->cls(\ord($s[$i + 1])) === self::K_ID) {
            $j = $this->identEnd($s, $len, $i + 1);
            $this->push(__McTokId::T_VARIABLE, \substr($s, $i, $j - $i), $line, $i);
            return $j;
        }

        if ($k === self::K_QUOTE) { return $this->scanQuote($s, $len, $i, $line, $b); }

        return $this->scanPunct($s, $len, $i, $line, $b);
    }

    /** End of the identifier starting at $i (its first byte is already ID class). */
    private function identEnd(string $s, int $len, int $i): int
    {
        $j = $i + 1;
        while ($j < $len) {
            $c = $this->cls(\ord($s[$j]));
            if ($c !== self::K_ID && $c !== self::K_DIGIT) { break; }
            $j = $j + 1;
        }
        return $j;
    }

    private function scanIdent(string $s, int $len, int $i, int $line): int
    {
        $j = $this->identEnd($s, $len, $i);
        $w = \substr($s, $i, $j - $i);
        $arrow = $this->afterArrow;
        // TOKEN_PARSE makes the lexer follow the PARSER's context, so a reserved
        // word standing where a member NAME belongs is an identifier. Measured:
        // it fires after `::` and after `function`. (Zend also throws ParseError
        // on invalid input under this flag; we do not — documented divergence.)
        if (($this->flags & 1) !== 0
            && ($this->afterDoubleColon !== 0 || $this->afterFunction !== 0)) {
            $arrow = 1;
        }

        // After `->` / `?->` a reserved word is just a property name. This is
        // why `$o->class` is T_STRING with no TOKEN_PARSE involved.
        if ($arrow === 0) {
            $pk = $this->parenKeyword($s, $len, $i, $j, $w);
            if ($pk > 0) {
                $end = $j + 5;
                $this->push($pk, \substr($s, $i, $end - $i), $line, $i);
                return $end;
            }
            $id = $this->keywordId($s, $i, $j - $i, $w);
            if ($id === __McTokId::T_YIELD) {
                $yf = $this->yieldFromEnd($s, $len, $j);
                if ($yf > 0) {
                    $this->push(__mc_tok_yield_from(), \substr($s, $i, $yf - $i), $line, $i);
                    $this->line = $line + $this->nl($s, $i, $yf);
                    return $yf;
                }
            }
            if ($id === __McTokId::T_NAMESPACE && $j < $len && \ord($s[$j]) === 92) {
                $e = $this->qualifiedEnd($s, $len, $j);
                if ($e > $j) {
                    $this->push(__McTokId::T_NAME_RELATIVE, \substr($s, $i, $e - $i), $line, $i);
                    return $e;
                }
            }
            if ($id !== __McTokId::T_STRING) {
                $this->push($id, $w, $line, $i);
                return $j;
            }
            // `enum` is CONTEXTUAL: a keyword only before whitespace + a name.
            if ($this->isEnumKeyword($s, $len, $w, $j)) {
                $this->push(__mc_tok_enum(), $w, $line, $i);
                return $j;
            }
        }

        // A qualified name swallows `\Seg` runs: Foo\Bar is ONE token.
        if ($j < $len && \ord($s[$j]) === 92) {
            $e = $this->qualifiedEnd($s, $len, $j);
            if ($e > $j) {
                $this->push(__McTokId::T_NAME_QUALIFIED, \substr($s, $i, $e - $i), $line, $i);
                return $e;
            }
        }
        $this->push(__McTokId::T_STRING, $w, $line, $i);
        return $j;
    }

    /** php 8.4 `public(set)` — ONE token, no whitespace tolerance. */
    private function parenKeyword(string $s, int $len, int $i, int $j, string $w): int
    {
        if ($j + 5 > $len) { return 0; }
        if (\substr($s, $j, 5) !== '(set)') { return 0; }
        $cand = \strtolower($w) . '(set)';
        return $this->parenKw[$cand] ?? 0;
    }

    /** End of a `\Seg\Seg` run starting at the backslash, or $at if none. */
    private function qualifiedEnd(string $s, int $len, int $at): int
    {
        $e = $at;
        while ($e < $len && \ord($s[$e]) === 92) {
            if ($e + 1 >= $len) { break; }
            if ($this->cls(\ord($s[$e + 1])) !== self::K_ID) { break; }
            $e = $this->identEnd($s, $len, $e + 1);
        }
        return $e;
    }

    private function isEnumKeyword(string $s, int $len, string $w, int $j): bool
    {
        if (\strtolower($w) !== 'enum') { return false; }
        $p = $j;
        $sawWs = false;
        while ($p < $len) {
            $c = \ord($s[$p]);
            if ($c !== 32 && $c !== 9 && $c !== 10 && $c !== 13) { break; }
            $sawWs = true;
            $p = $p + 1;
        }
        if (!$sawWs || $p >= $len) { return false; }
        return $this->cls(\ord($s[$p])) === self::K_ID;
    }

    /** End of `yield from` counted from just after `yield`, or 0. */
    private function yieldFromEnd(string $s, int $len, int $j): int
    {
        $p = $j;
        while ($p < $len) {
            $c = \ord($s[$p]);
            if ($c !== 32 && $c !== 9 && $c !== 10 && $c !== 13) { break; }
            $p = $p + 1;
        }
        if ($p === $j || $p + 4 > $len) { return 0; }
        if (\strtolower(\substr($s, $p, 4)) !== 'from') { return 0; }
        $e = $p + 4;
        if ($e < $len) {
            $c = $this->cls(\ord($s[$e]));
            if ($c === self::K_ID || $c === self::K_DIGIT) { return 0; }
        }
        return $e;
    }

    /**
     * Case-insensitive keyword lookup with no allocation on the common path:
     * one hash probe on the string substr already produced. A non-lowercase
     * keyword is rare, and proving its absence costs only a byte walk.
     */
    private function keywordId(string $s, int $at, int $n, string $w): int
    {
        if ($n > 15) { return __McTokId::T_STRING; }
        $id = $this->kw[$w] ?? 0;
        if ($id !== 0) { return $id; }
        $id = $this->magic[$w] ?? 0;
        if ($id !== 0) { return $id; }
        $j = 0;
        while ($j < $n) {
            $c = \ord($s[$at + $j]);
            if ($c >= 65 && $c <= 90) {
                $lc = \strtolower($w);
                $id = $this->kw[$lc] ?? 0;
                if ($id !== 0) { return $id; }
                return $this->magic[$lc] ?? __McTokId::T_STRING;
            }
            $j = $j + 1;
        }
        return __McTokId::T_STRING;
    }

    private function scanNumber(string $s, int $len, int $i, int $line): int
    {
        $j = $i;
        $isFloat = false;
        $b = \ord($s[$i]);
        if ($b === 48 && $i + 1 < $len) {
            $x = \ord($s[$i + 1]) | 32;
            if ($x === 120 || $x === 111 || $x === 98) {
                $j = $i + 2;
                while ($j < $len) {
                    $c = \ord($s[$j]);
                    $ck = $this->cls($c);
                    if ($ck !== self::K_DIGIT && $ck !== self::K_ID && $c !== 95) { break; }
                    $j = $j + 1;
                }
                $text = \substr($s, $i, $j - $i);
                $id = $this->intOverflows($text) ? __McTokId::T_DNUMBER : __McTokId::T_LNUMBER;
                $this->push($id, $text, $line, $i);
                return $j;
            }
        }
        while ($j < $len) {
            $c = \ord($s[$j]);
            if ($this->cls($c) === self::K_DIGIT || $c === 95) { $j = $j + 1; continue; }
            break;
        }
        if ($j < $len && \ord($s[$j]) === 46 && $j + 1 < $len
            && $this->cls(\ord($s[$j + 1])) === self::K_DIGIT) {
            $isFloat = true;
            $j = $j + 1;
            while ($j < $len) {
                $c = \ord($s[$j]);
                if ($this->cls($c) === self::K_DIGIT || $c === 95) { $j = $j + 1; continue; }
                break;
            }
        }
        if ($j < $len && (\ord($s[$j]) | 32) === 101) {
            $p = $j + 1;
            if ($p < $len && (\ord($s[$p]) === 43 || \ord($s[$p]) === 45)) { $p = $p + 1; }
            if ($p < $len && $this->cls(\ord($s[$p])) === self::K_DIGIT) {
                $isFloat = true;
                $j = $p;
                while ($j < $len && $this->cls(\ord($s[$j])) === self::K_DIGIT) { $j = $j + 1; }
            }
        }
        $text = \substr($s, $i, $j - $i);
        $id = __McTokId::T_LNUMBER;
        if ($isFloat || $this->intOverflows($text)) { $id = __McTokId::T_DNUMBER; }
        $this->push($id, $text, $line, $i);
        return $j;
    }

    /** An integer literal too large for int is T_DNUMBER, not T_LNUMBER. */
    private function intOverflows(string $text): bool
    {
        // Decided by STRING COMPARISON against PHP_INT_MAX in the literal's own
        // base — never by coercing and asking is_int(). Coercion is exactly the
        // path that is unreliable here: natively `"1" + 0` prints int(1) while
        // both is_int() and is_float() answer false, and an over-large decimal
        // saturates to PHP_INT_MAX instead of becoming a float. Comparing digits
        // is exact, allocation-cheap, and identical under both interpreters.
        $clean = \str_replace('_', '', $text);
        $n = \strlen($clean);
        $digits = $clean;
        $limit = '9223372036854775807';
        if ($n > 1 && \ord($clean[0]) === 48) {
            $x = \ord($clean[1]) | 32;
            if ($x === 120) { $digits = \strtolower(\substr($clean, 2)); $limit = '7fffffffffffffff'; }
            elseif ($x === 98) { $digits = \substr($clean, 2); $limit = '111111111111111111111111111111111111111111111111111111111111111'; }
            elseif ($x === 111) { $digits = \substr($clean, 2); $limit = '777777777777777777777'; }
            else { $digits = \substr($clean, 1); $limit = '777777777777777777777'; }
        }
        $i = 0;
        $dl = \strlen($digits);
        while ($i < $dl - 1 && \ord($digits[$i]) === 48) { $i = $i + 1; }
        $digits = \substr($digits, $i);
        $dl = \strlen($digits);
        $ll = \strlen($limit);
        if ($dl > $ll) { return true; }
        if ($dl < $ll) { return false; }
        return \strcmp($digits, $limit) > 0;
    }

    private function scanQuote(string $s, int $len, int $i, int $line, int $b): int
    {
        if ($b === 39) { return $this->scanSingle($s, $len, $i, $line); }
        // A double-quoted string with no interpolation trigger is ONE
        // T_CONSTANT_ENCAPSED_STRING; otherwise it opens a state.
        if ($b === 34) {
            $end = $this->plainDqEnd($s, $len, $i);
            if ($end > 0) {
                $text = \substr($s, $i, $end - $i);
                $this->push(__McTokId::T_CONSTANT_ENCAPSED_STRING, $text, $line, $i);
                $this->line = $line + $this->nl($s, $i, $end);
                return $end;
            }
            $this->push(34, '"', $line, $i);
            $this->stStack[] = $this->st;
            $this->st = self::ST_DQ;
            return $i + 1;
        }
        $this->push(96, '`', $line, $i);
        $this->stStack[] = $this->st;
        $this->st = self::ST_BT;
        return $i + 1;
    }

    private function scanSingle(string $s, int $len, int $i, int $line): int
    {
        $j = $i + 1;
        while ($j < $len) {
            $c = \ord($s[$j]);
            if ($c === 92) { $j = $j + 2; continue; }
            if ($c === 39) { $j = $j + 1; break; }
            $j = $j + 1;
        }
        if ($j > $len) { $j = $len; }
        $text = \substr($s, $i, $j - $i);
        $this->push(__McTokId::T_CONSTANT_ENCAPSED_STRING, $text, $line, $i);
        $this->line = $line + $this->nl($s, $i, $j);
        return $j;
    }

    /** End of a double-quoted string with NO interpolation, else 0. */
    private function plainDqEnd(string $s, int $len, int $i): int
    {
        $j = $i + 1;
        while ($j < $len) {
            $c = \ord($s[$j]);
            if ($c === 92) { $j = $j + 2; continue; }
            if ($c === 34) { return $j + 1; }
            if ($c === 36 && $j + 1 < $len) {
                $nx = \ord($s[$j + 1]);
                if ($this->cls($nx) === self::K_ID || $nx === 123) { return 0; }
            }
            if ($c === 123 && $j + 1 < $len && \ord($s[$j + 1]) === 36) { return 0; }
            $j = $j + 1;
        }
        return 0;
    }

    /** Inside "…", `…`, or a heredoc body. */
    private function scanEncaps(string $s, int $len, int $i, int $line = 0): int
    {
        $line = $this->line;
        $st = $this->st;
        $term = $st === self::ST_DQ ? 34 : ($st === self::ST_BT ? 96 : -1);
        // A NOWDOC body is raw: `$v` and `{$v}` are literal text, and only the
        // terminator ends the run.
        $raw = $st === self::ST_NOWDOC;
        $start = $i;
        $j = $i;
        while ($j < $len) {
            $c = \ord($s[$j]);
            if ($c === 92 && $term >= 0) { $j = $j + 2; continue; }
            if ($c === $term) { break; }
            if ($term < 0 && $this->heredocEndAt($s, $len, $j) >= 0) { break; }
            if ($raw) { $j = $j + 1; continue; }
            if ($c === 36 && $j + 1 < $len) {
                $nx = \ord($s[$j + 1]);
                if ($this->cls($nx) === self::K_ID || $nx === 123) { break; }
            }
            if ($c === 123 && $j + 1 < $len && \ord($s[$j + 1]) === 36) { break; }
            $j = $j + 1;
        }
        if ($j > $len) { $j = $len; }
        if ($j > $start) {
            $text = \substr($s, $start, $j - $start);
            $this->push(__McTokId::T_ENCAPSED_AND_WHITESPACE, $text, $line, $start);
            $this->line = $line + $this->nl($s, $start, $j);
        }
        if ($j >= $len) { return $len; }

        $line = $this->line;
        $c = \ord($s[$j]);
        if ($term >= 0 && $c === $term) {
            $this->push($term, $term === 34 ? '"' : '`', $line, $j);
            $this->st = (int) \array_pop($this->stStack);
            return $j + 1;
        }
        if ($term < 0) {
            $e = $this->heredocEndAt($s, $len, $j);
            if ($e >= 0) { return $this->pushHeredocEnd($s, $j, $e, $line); }
        }
        if ($c === 123) {
            $this->push(__McTokId::T_CURLY_OPEN, '{', $line, $j);
            $this->stStack[] = $this->st;
            $this->st = self::ST_PHP;
            $this->curlyDepth = 0;
            return $j + 1;
        }
        // `$`
        $nx = \ord($s[$j + 1]);
        if ($nx === 123) {
            $this->push(__McTokId::T_DOLLAR_OPEN_CURLY_BRACES, '${', $line, $j);
            $this->stStack[] = $this->st;
            $this->st = self::ST_VARNAME;
            return $j + 2;
        }
        $e = $this->identEnd($s, $len, $j + 1);
        $this->push(__McTokId::T_VARIABLE, \substr($s, $j, $e - $j), $line, $j);
        if ($e < $len && \ord($s[$e]) === 91) {
            $this->push(91, '[', $line, $e);
            $this->stStack[] = $this->st;
            $this->st = self::ST_OFFSET;
            return $e + 1;
        }
        if ($e + 1 < $len && \ord($s[$e]) === 45 && \ord($s[$e + 1]) === 62
            && $e + 2 < $len && $this->cls(\ord($s[$e + 2])) === self::K_ID) {
            $this->push(__McTokId::T_OBJECT_OPERATOR, '->', $line, $e);
            $pe = $this->identEnd($s, $len, $e + 2);
            $this->push(__McTokId::T_STRING, \substr($s, $e + 2, $pe - $e - 2), $line, $e + 2);
            return $pe;
        }
        return $e;
    }

    /** Inside `$a[…]` in a string: only three token shapes are legal. */
    private function scanOffset(string $s, int $len, int $i): int
    {
        $line = $this->line;
        $b = \ord($s[$i]);
        if ($b === 93) {
            $this->push(93, ']', $line, $i);
            $this->st = (int) \array_pop($this->stStack);
            return $i + 1;
        }
        if ($this->cls($b) === self::K_DIGIT || $b === 45) {
            $j = $b === 45 ? $i + 1 : $i;
            while ($j < $len && $this->cls(\ord($s[$j])) === self::K_DIGIT) { $j = $j + 1; }
            $this->push(__McTokId::T_NUM_STRING, \substr($s, $i, $j - $i), $line, $i);
            return $j;
        }
        if ($b === 36 && $i + 1 < $len && $this->cls(\ord($s[$i + 1])) === self::K_ID) {
            $j = $this->identEnd($s, $len, $i + 1);
            $this->push(__McTokId::T_VARIABLE, \substr($s, $i, $j - $i), $line, $i);
            return $j;
        }
        if ($this->cls($b) === self::K_ID) {
            $j = $this->identEnd($s, $len, $i);
            $this->push(__McTokId::T_STRING, \substr($s, $i, $j - $i), $line, $i);
            return $j;
        }
        $this->push($b, $this->chr[$b], $line, $i);
        return $i + 1;
    }

    /** After `${`: a bare name then `}`, else fall back to full PHP. */
    private function scanVarname(string $s, int $len, int $i): int
    {
        $line = $this->line;
        if ($this->cls(\ord($s[$i])) === self::K_ID) {
            $j = $this->identEnd($s, $len, $i);
            if ($j < $len && (\ord($s[$j]) === 125 || \ord($s[$j]) === 91)) {
                $this->push(__McTokId::T_STRING_VARNAME, \substr($s, $i, $j - $i), $line, $i);
                $this->st = self::ST_PHP;
                $this->curlyDepth = 0;
                return $j;
            }
        }
        $this->st = self::ST_PHP;
        $this->curlyDepth = 0;
        return $i;
    }

    /** Offset of the heredoc terminator's label at $j, or -1. */
    private function heredocEndAt(string $s, int $len, int $j): int
    {
        if ($this->hdLabel === []) { return -1; }
        if ($j > 0 && \ord($s[$j - 1]) !== 10) { return -1; }
        $label = $this->hdLabel[\count($this->hdLabel) - 1];
        $p = $j;
        while ($p < $len) {
            $c = \ord($s[$p]);
            if ($c !== 32 && $c !== 9) { break; }
            $p = $p + 1;
        }
        $ll = \strlen($label);
        if ($p + $ll > $len) { return -1; }
        if (\substr($s, $p, $ll) !== $label) { return -1; }
        $after = $p + $ll;
        if ($after < $len) {
            $c = $this->cls(\ord($s[$after]));
            if ($c === self::K_ID || $c === self::K_DIGIT) { return -1; }
        }
        return $p;
    }

    /** The closing marker's INDENT belongs to T_END_HEREDOC's own text. */
    private function pushHeredocEnd(string $s, int $j, int $labelAt, int $line): int
    {
        $label = (string) \array_pop($this->hdLabel);
        $end = $labelAt + \strlen($label);
        $this->push(__McTokId::T_END_HEREDOC, \substr($s, $j, $end - $j), $line, $j);
        $this->st = (int) \array_pop($this->stStack);
        return $end;
    }

    private function scanHeredocStart(string $s, int $len, int $i, int $line): int
    {
        $p = $i + 3;
        while ($p < $len) {
            $c = \ord($s[$p]);
            if ($c !== 32 && $c !== 9) { break; }
            $p = $p + 1;
        }
        $quote = 0;
        if ($p < $len && (\ord($s[$p]) === 34 || \ord($s[$p]) === 39)) {
            $quote = \ord($s[$p]);
            $p = $p + 1;
        }
        if ($p >= $len || $this->cls(\ord($s[$p])) !== self::K_ID) {
            return $this->pushBad($s, $i, $line);
        }
        $le = $this->identEnd($s, $len, $p);
        $label = \substr($s, $p, $le - $p);
        $q = $le;
        if ($quote !== 0) {
            if ($q >= $len || \ord($s[$q]) !== $quote) { return $this->pushBad($s, $i, $line); }
            $q = $q + 1;
        }
        if ($q < $len && \ord($s[$q]) === 13) { $q = $q + 1; }
        if ($q >= $len || \ord($s[$q]) !== 10) { return $this->pushBad($s, $i, $line); }
        $q = $q + 1;
        $this->push(__McTokId::T_START_HEREDOC, \substr($s, $i, $q - $i), $line, $i);
        $this->line = $line + $this->nl($s, $i, $q);
        $this->hdLabel[] = $label;
        $this->stStack[] = $this->st;
        $this->st = $quote === 39 ? self::ST_NOWDOC : self::ST_HEREDOC;
        return $q;
    }

    private function pushBad(string $s, int $i, int $line): int
    {
        $this->push(__McTokId::T_BAD_CHARACTER, $this->chr[\ord($s[$i])], $line, $i);
        return $i + 1;
    }

    /** Comments, tags, casts, operators, and the bare single-byte tokens. */
    private function scanPunct(string $s, int $len, int $i, int $line, int $b): int
    {
        // `#[` is an attribute and MUST be tested before the `#` comment.
        if ($b === 35 && $i + 1 < $len && \ord($s[$i + 1]) === 91) {
            $this->push(__McTokId::T_ATTRIBUTE, '#[', $line, $i);
            return $i + 2;
        }
        if ($b === 35) { return $this->scanLineComment($s, $len, $i, $line); }
        if ($b === 47 && $i + 1 < $len) {
            $nx = \ord($s[$i + 1]);
            if ($nx === 47) { return $this->scanLineComment($s, $len, $i, $line); }
            if ($nx === 42) { return $this->scanBlockComment($s, $len, $i, $line); }
        }
        if ($b === 63 && $i + 1 < $len && \ord($s[$i + 1]) === 62) {
            return $this->scanCloseTag($s, $len, $i, $line);
        }
        // A leading `\` that joins a name is part of it: `\Foo\Bar` is ONE
        // T_NAME_FULLY_QUALIFIED. A `\` that joins nothing stays T_NS_SEPARATOR.
        if ($b === 92) {
            $e = $this->qualifiedEnd($s, $len, $i);
            if ($e > $i) {
                $this->push(__McTokId::T_NAME_FULLY_QUALIFIED, \substr($s, $i, $e - $i), $line, $i);
                return $e;
            }
            $this->push(__McTokId::T_NS_SEPARATOR, '\\', $line, $i);
            return $i + 1;
        }
        if ($b === 60 && $i + 2 < $len && \ord($s[$i + 1]) === 60 && \ord($s[$i + 2]) === 60) {
            return $this->scanHeredocStart($s, $len, $i, $line);
        }
        if ($b === 40) {
            $e = $this->castEnd($s, $len, $i);
            if ($e > 0) {
                $inner = \strtolower(\trim(\substr($s, $i + 1, $e - $i - 2)));
                $id = $this->casts[$inner] ?? 0;
                if ($id !== 0) {
                    $this->push($id, \substr($s, $i, $e - $i), $line, $i);
                    return $e;
                }
            }
        }
        if ($b === 38) {
            $id = $this->ampFollowedByVar($s, $len, $i + 1)
                ? __mc_tok_amp_followed() : __mc_tok_amp_plain();
            // `&&` and `&=` are ordinary operators and win over the lone `&`.
            $two = $i + 1 < $len ? \substr($s, $i, 2) : '';
            if ($two !== '' && isset($this->ops[$two])) {
                $this->push($this->ops[$two], $two, $line, $i);
                return $i + 2;
            }
            $this->push($id, '&', $line, $i);
            return $i + 1;
        }

        $take = \ord($this->opLead[$b]) === 49 ? 3 : 1;
        while ($take > 1) {
            if ($i + $take <= $len) {
                $cand = \substr($s, $i, $take);
                $id = $this->ops[$cand] ?? 0;
                if ($id !== 0) {
                    $this->push($id, $cand, $line, $i);
                    return $i + $take;
                }
            }
            $take = $take - 1;
        }

        if ($this->cls($b) === self::K_OTHER) { return $this->pushBad($s, $i, $line); }

        // A single byte is a BARE STRING in the legacy shape: its id IS its byte.
        if ($b === 123 && $this->curlyDepth >= 0) { $this->curlyDepth = $this->curlyDepth + 1; }
        if ($b === 125 && $this->curlyDepth >= 0) {
            if ($this->curlyDepth === 0) {
                $this->push(125, '}', $line, $i);
                $this->st = (int) \array_pop($this->stStack);
                $this->curlyDepth = -1;
                return $i + 1;
            }
            $this->curlyDepth = $this->curlyDepth - 1;
        }
        $this->push($b, $this->chr[$b], $line, $i);
        // `__halt_compiler(); …` — everything after the semicolon is ONE
        // T_INLINE_HTML, whatever it contains. The data section of a phar.
        if ($b === 59 && $this->halt === 1) {
            $this->halt = 0;
            $rest = $i + 1;
            if ($rest < $len) {
                $this->push(__McTokId::T_INLINE_HTML, \substr($s, $rest), $this->line, $rest);
            }
            return $len;
        }
        return $i + 1;
    }

    /** Next non-whitespace starts `$var` or `...` — decides which `&` this is. */
    private function ampFollowedByVar(string $s, int $len, int $p): bool
    {
        while ($p < $len) {
            $c = \ord($s[$p]);
            if ($c !== 32 && $c !== 9 && $c !== 10 && $c !== 13) { break; }
            $p = $p + 1;
        }
        if ($p >= $len) { return false; }
        $c = \ord($s[$p]);
        if ($c === 36) { return true; }
        return $c === 46 && $p + 2 < $len && \ord($s[$p + 1]) === 46 && \ord($s[$p + 2]) === 46;
    }

    /** End of a cast `( word )` including the paren, or 0. */
    private function castEnd(string $s, int $len, int $i): int
    {
        $p = $i + 1;
        while ($p < $len) {
            $c = \ord($s[$p]);
            if ($c !== 32 && $c !== 9) { break; }
            $p = $p + 1;
        }
        if ($p >= $len || $this->cls(\ord($s[$p])) !== self::K_ID) { return 0; }
        $we = $this->identEnd($s, $len, $p);
        $q = $we;
        while ($q < $len) {
            $c = \ord($s[$q]);
            if ($c !== 32 && $c !== 9) { break; }
            $q = $q + 1;
        }
        if ($q >= $len || \ord($s[$q]) !== 41) { return 0; }
        return $q + 1;
    }

    /** `//` and `#` stop at a newline OR at `?>`, which stays a real close tag. */
    private function scanLineComment(string $s, int $len, int $i, int $line): int
    {
        $j = $i;
        while ($j < $len) {
            $c = \ord($s[$j]);
            if ($c === 10) { break; }
            if ($c === 63 && $j + 1 < $len && \ord($s[$j + 1]) === 62) { break; }
            $j = $j + 1;
        }
        $this->push(__McTokId::T_COMMENT, \substr($s, $i, $j - $i), $line, $i);
        return $j;
    }

    /**
     * A doc comment needs `/**` FOLLOWED BY WHITESPACE. `/**\/`, `/***\/` and
     * `/**d*\/` are plain T_COMMENT — measured, not guessed.
     */
    private function scanBlockComment(string $s, int $len, int $i, int $line): int
    {
        $j = $i + 2;
        while ($j < $len) {
            if (\ord($s[$j]) === 42 && $j + 1 < $len && \ord($s[$j + 1]) === 47) {
                $j = $j + 2;
                break;
            }
            $j = $j + 1;
        }
        if ($j > $len) { $j = $len; }
        $id = __McTokId::T_COMMENT;
        if ($j - $i >= 5 && \ord($s[$i + 2]) === 42) {
            $w = \ord($s[$i + 3]);
            if ($w === 32 || $w === 9 || $w === 10 || $w === 13) { $id = __McTokId::T_DOC_COMMENT; }
        }
        $this->push($id, \substr($s, $i, $j - $i), $line, $i);
        $this->line = $line + $this->nl($s, $i, $j);
        return $j;
    }

    /** `?>` absorbs one following newline into its own text. */
    private function scanCloseTag(string $s, int $len, int $i, int $line): int
    {
        $j = $i + 2;
        if ($j < $len && \ord($s[$j]) === 13) { $j = $j + 1; }
        if ($j < $len && \ord($s[$j]) === 10) { $j = $j + 1; }
        $this->push(__McTokId::T_CLOSE_TAG, \substr($s, $i, $j - $i), $line, $i);
        $this->line = $line + $this->nl($s, $i, $j);
        $this->st = self::ST_HTML;
        return $j;
    }
}
