<?php

/**
 * Generates src/Runtime/Stdlib/MbstringTables.php FROM ZEND's ext/mbstring.
 *
 * Nothing is hand-typed: the encoding list, every alias and MIME name, and each
 * single-byte encoding's byte → codepoint table are read back from Zend
 * (mb_list_encodings / mb_encoding_aliases / mb_preferred_mime_name /
 * mb_convert_encoding byte by byte), so a name Zend accepts is a name we accept
 * and a byte Zend cannot map is a byte we cannot map.
 *
 *   php -d xdebug.mode=off tools/gen_mbstring_tables.php
 */

if (!\extension_loaded('mbstring')) {
    \fwrite(STDERR, "needs php with ext/mbstring\n");
    exit(2);
}
\error_reporting(E_ALL & ~E_DEPRECATED);

// The encodings whose every byte is one character (MBFL_ENCTYPE_SBCS in Zend).
$sbcs = ['7bit', '8bit', 'ASCII', 'Windows-1252', 'Windows-1254', 'Windows-1251', 'CP866', 'CP850',
    'KOI8-R', 'KOI8-U', 'ArmSCII-8'];
foreach (\mb_list_encodings() as $e) {
    if (\str_starts_with($e, 'ISO-8859-')) { $sbcs[] = $e; }
}

$list = \mb_list_encodings();
$aliases = [];
$mime = [];
foreach ($list as $e) {
    $aliases[$e] = \mb_encoding_aliases($e);
    try {
        $m = @\mb_preferred_mime_name($e);
        $mime[$e] = $m === false ? '' : $m;
    } catch (\ValueError $x) {
        $mime[$e] = '';
    }
}

\mb_substitute_character('none');
$tables = [];
foreach ($sbcs as $e) {
    if (!\in_array($e, $list, true)) { throw new \RuntimeException("not an mbstring encoding: $e"); }
    $high = [];
    for ($b = 0; $b < 256; $b++) {
        $u = \mb_convert_encoding(\chr($b), 'UTF-8', $e);
        $cp = $u === '' ? -1 : \mb_ord($u, 'UTF-8');
        if ($b < 0x80) {
            // The fast paths assume an ASCII-compatible low half (7bit/ASCII included).
            if ($cp !== $b) { throw new \RuntimeException("$e: byte $b is not ASCII-identical"); }
            continue;
        }
        $high[] = $cp;
    }
    $tables[$e] = $high;
}

$php = \PHP_VERSION;
$out = "<?php\n\n// GENERATED by tools/gen_mbstring_tables.php from php $php ext/mbstring — do not edit.\n\n";
$out .= "/**\n * Every encoding mbstring knows, in mb_list_encodings() order.\n * @return string[]\n */\n";
$out .= "function __mc_mb_list(): array\n{\n    return " . export($list) . ";\n}\n\n";
$out .= "/**\n * Aliases per canonical name, as mb_encoding_aliases() answers.\n * @return array<string,string[]>\n */\n";
$out .= "function __mc_mb_alias_table(): array\n{\n    return " . export($aliases) . ";\n}\n\n";
$out .= "/**\n * Preferred MIME name per canonical name, \"\" when there is none.\n * @return array<string,string>\n */\n";
$out .= "function __mc_mb_mime_table(): array\n{\n    return " . export($mime) . ";\n}\n\n";
$out .= "/**\n * Single-byte encodings: codepoint of each byte 0x80..0xFF (-1 = unmapped).\n * The low half is ASCII for all of them (checked at generation).\n * @return array<string,int[]>\n */\n";
$out .= "function __mc_mb_sbcs_tables(): array\n{\n    return " . export($tables) . ";\n}\n";
\file_put_contents(__DIR__ . '/../src/Runtime/Stdlib/MbstringTables.php', $out);
echo \count($list), " encodings, ", \count($tables), " single-byte tables\n";

function export(array $a): string
{
    $isList = \array_is_list($a);
    $parts = [];
    foreach ($a as $k => $v) {
        $val = \is_array($v) ? export($v) : (\is_int($v) ? (string)$v : \var_export($v, true));
        $parts[] = $isList ? $val : \var_export($k, true) . ' => ' . $val;
    }
    if ($parts === []) { return '[]'; }
    $flat = \is_int($a[\array_key_first($a)] ?? null);
    return $flat ? '[' . \implode(', ', $parts) . ']' : "[\n        " . \implode(",\n        ", $parts) . ",\n    ]";
}
