<?php

/**
 * Generates every ext/tokenizer lookup table FROM ZEND, under the seed `php`.
 *
 * Nothing here is hand-typed: the T_* ids come from get_defined_constants(), and
 * every keyword / cast / magic-constant / operator id is recovered by handing
 * Zend the spelling and reading back the token it produced. A wrong spelling is
 * therefore a hard failure at generation time, not a silently wrong id far away.
 *
 *   php tools/gen_tokenizer_tables.php          # rewrite the tables
 *   php tools/gen_tokenizer_tables.php --check  # fail if the tree disagrees
 *
 * Two outputs:
 *   src/Compile/Mir/Passes/TokenizerConsts.php  compiler side: T_* name -> int,
 *                                               folded by LowerPrelude
 *   prelude/tokenizer.php                       runtime side: the region between
 *                                               the GENERATED markers
 *
 * T_* VALUES ARE NOT STABLE ACROSS PHP VERSIONS. The generated files record the
 * version they came from; --check refuses to pass on a different host.
 */

const ROOT = __DIR__ . '/..';
const CONSTS_FILE = ROOT . '/src/Compile/Mir/Passes/TokenizerConsts.php';
const PRELUDE_FILE = ROOT . '/prelude/tokenizer.php';
const BEGIN = '// ---8<--- GENERATED by tools/gen_tokenizer_tables.php — do not edit ---8<---';
const END = '// ---8<--- END GENERATED ---8<---';

$check = in_array('--check', $argv, true);

if (!extension_loaded('tokenizer')) {
    fwrite(STDERR, "the seed php has no ext/tokenizer — cannot generate\n");
    exit(1);
}

/** Every reserved spelling that Zend maps to a token of its own. */
const KEYWORDS = [
    'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch',
    'class', 'clone', 'const', 'continue', 'declare', 'default', 'die', 'do',
    'echo', 'else', 'elseif', 'empty', 'enddeclare', 'endfor', 'endforeach',
    'endif', 'endswitch', 'endwhile', 'enum', 'eval', 'exit', 'extends',
    'final', 'finally', 'fn', 'for', 'foreach', 'function', 'global', 'goto',
    'if', 'implements', 'include', 'include_once', 'instanceof', 'insteadof',
    'interface', 'isset', 'list', 'match', 'namespace', 'new', 'or', 'print',
    'private', 'protected', 'public', 'readonly', 'require', 'require_once',
    'return', 'static', 'switch', 'throw', 'trait', 'try', 'unset', 'use',
    'var', 'while', 'xor', 'yield', '__halt_compiler',
];

const MAGIC = [
    '__line__', '__file__', '__dir__', '__function__', '__class__',
    '__trait__', '__method__', '__namespace__', '__property__',
];

/** Cast spellings, canonical + alias. The scanner normalises whitespace/case. */
const CASTS = [
    '(int)', '(integer)', '(bool)', '(boolean)', '(float)', '(double)',
    '(real)', '(string)', '(array)', '(object)', '(unset)', '(void)',
];

/**
 * Spellings Zend fuses into ONE token even though they contain punctuation:
 * php 8.4's asymmetric visibility. `public(set)` is a single T_PUBLIC_SET, not
 * `public` `(` `set` `)`.
 */
const PAREN_KEYWORDS = ['public(set)', 'protected(set)', 'private(set)'];

/** Multi-byte operators. Single bytes are BARE STRINGS in Zend and need no id. */
const OPERATORS = [
    '===', '!==', '==', '!=', '<>', '<=>', '<=', '>=', '&&', '||', '??', '??=',
    '++', '--', '+=', '-=', '*=', '/=', '.=', '%=', '**=', '**', '&=', '|=',
    '^=', '<<=', '>>=', '<<', '>>', '=>', '->', '?->', '::', '...', '#[',
    '&&=', '|>',
];

/** Hand the spelling to Zend inside a minimal program; return the token ids. */
function idsOf(string $code): array
{
    $out = [];
    foreach (@token_get_all('<?php ' . $code) as $t) {
        if (is_string($t)) { $out[] = ['s', $t]; continue; }
        if ($t[0] === T_OPEN_TAG || $t[0] === T_WHITESPACE) { continue; }
        $out[] = ['i', $t[0], $t[1]];
    }
    return $out;
}

/** The one id a spelling must produce, or null when Zend does not fuse it. */
function soleId(string $code): ?int
{
    $ids = idsOf($code);
    if (count($ids) !== 1 || $ids[0][0] !== 'i') { return null; }
    return $ids[0][1];
}

// ── T_* constants, straight from the host ──────────────────────────────
$tokenConsts = get_defined_constants(true)['tokenizer'] ?? [];
ksort($tokenConsts);
$names = [];
foreach ($tokenConsts as $n => $v) {
    if (!is_int($v)) { continue; }
    $names[$n] = $v;
}
if (!isset($names['T_STRING'], $names['T_VARIABLE'], $names['T_WHITESPACE'])) {
    fwrite(STDERR, "the tokenizer constant set looks wrong\n");
    exit(1);
}
$names['TOKEN_PARSE'] = TOKEN_PARSE;

// id -> canonical name. Zend aliases a few ids (T_DOUBLE_COLON/T_PAAMAYIM_NEKUDOTAYIM),
// so keep the FIRST name for the reverse map, which is what token_name() returns.
$reverse = [];
foreach ($names as $n => $v) {
    if ($n === 'TOKEN_PARSE') { continue; }
    if (!isset($reverse[$v])) { $reverse[$v] = token_name($v); }
}
ksort($reverse);

// ── keyword / magic / cast / operator ids, recovered from Zend ──────────
$kw = [];
foreach (KEYWORDS as $w) {
    $id = soleId($w);
    if ($id === null) { fwrite(STDERR, "keyword '$w' did not fuse to one token\n"); exit(1); }
    $kw[$w] = $id;
}
// `yield from` is ONE token whose text spans the inner whitespace.
$yieldFrom = soleId('yield from');
if ($yieldFrom === null) { fwrite(STDERR, "yield from did not fuse\n"); exit(1); }

$parenKw = [];
foreach (PAREN_KEYWORDS as $w) {
    $id = soleId($w);
    if ($id === null) { fwrite(STDERR, "'$w' did not fuse to one token\n"); exit(1); }
    $parenKw[$w] = $id;
}

// `enum` is CONTEXTUAL: T_ENUM only before whitespace + an identifier, else
// T_STRING. The keyword table above therefore holds its T_STRING id, and the
// scanner promotes it on lookahead.
$enumId = soleId('enum');
$ids = idsOf('enum Foo');
if (count($ids) !== 2 || $ids[0][1] === $enumId) {
    fwrite(STDERR, "the `enum` contextual rule did not reproduce\n"); exit(1);
}
$enumKeywordId = $ids[0][1];

// `&` is decided by LOOKAHEAD, not context: it is one token if the next
// non-whitespace byte starts a variable or `...`, another token otherwise.
$ampFollowed = null;
$ampPlain = null;
foreach (idsOf('&$a') as $t) { if ($t[0] === 'i') { $ampFollowed = $t[1]; break; } }
foreach (idsOf('1&2') as $t) {
    if ($t[0] === 'i' && $t[2] === '&') { $ampPlain = $t[1]; break; }
}
if ($ampFollowed === null || $ampPlain === null || $ampFollowed === $ampPlain) {
    fwrite(STDERR, "the `&` lookahead rule did not reproduce\n"); exit(1);
}

$magic = [];
foreach (MAGIC as $w) {
    $id = soleId($w);
    if ($id === null) { fwrite(STDERR, "magic constant '$w' did not fuse\n"); exit(1); }
    $magic[$w] = $id;
}

$casts = [];
foreach (CASTS as $c) {
    $id = soleId($c . '$x');
    // `(int)$x` is two tokens: the cast and the variable.
    $ids = idsOf($c . '$x');
    if (count($ids) !== 2 || $ids[0][0] !== 'i') {
        fwrite(STDERR, "cast '$c' did not produce a cast token\n"); exit(1);
    }
    $inner = strtolower(trim(substr($c, 1, -1)));
    $casts[$inner] = $ids[0][1];
}

$ops = [];
$bare = [];
foreach (OPERATORS as $o) {
    $ids = idsOf($o);
    if (count($ids) === 1 && $ids[0][0] === 'i') { $ops[$o] = $ids[0][1]; continue; }
    if (count($ids) === 1 && $ids[0][0] === 's') { $bare[] = $o; continue; }
    // Zend split it — not a single token, so the scanner must not fuse it either.
    $bare[] = $o . ' (split)';
}

// ── which T_* ids no table covers: the completeness ledger ──────────────
$covered = array_flip(array_merge(
    array_values($kw), array_values($magic), array_values($casts),
    array_values($ops), array_values($parenKw),
    [$yieldFrom, $enumKeywordId, $ampFollowed, $ampPlain]
));
$dynamic = [];
foreach ($reverse as $id => $n) {
    if (!isset($covered[$id])) { $dynamic[$id] = $n; }
}

// ── emit ───────────────────────────────────────────────────────────────
function phpIntMap(array $m, int $indent): string
{
    $pad = str_repeat(' ', $indent);
    $out = '';
    foreach ($m as $k => $v) {
        $out .= $pad . var_export((string) $k, true) . ' => ' . $v . ",\n";
    }
    return $out;
}

function phpStrMap(array $m, int $indent): string
{
    $pad = str_repeat(' ', $indent);
    $out = '';
    foreach ($m as $k => $v) {
        $out .= $pad . $k . ' => ' . var_export((string) $v, true) . ",\n";
    }
    return $out;
}

$ver = PHP_VERSION;

$constsSrc = "<?php\n\nnamespace Compile\\Mir\\Passes;\n\n"
    . "/**\n"
    . " * ext/tokenizer's T_* constants, GENERATED by tools/gen_tokenizer_tables.php\n"
    . " * from php {$ver}. Do not edit — regenerate.\n"
    . " *\n"
    . " * These ids are NOT stable across php versions. Mirroring Zend's exact values is\n"
    . " * what lets `var_dump(token_get_all(...))` be diffed byte-for-byte against the\n"
    . " * interpreter, which is the only oracle this feature has.\n"
    . " */\n"
    . "final class TokenizerConsts\n{\n"
    . "    public const GENERATED_FROM = " . var_export($ver, true) . ";\n\n"
    . "    /** T_* (and TOKEN_PARSE) name -> value. @return array<string,int> */\n"
    . "    public static function ints(): array\n    {\n        return [\n"
    . phpIntMap($names, 12)
    . "        ];\n    }\n}\n";

// The scanner cannot name T_WHITESPACE directly: prelude/tokenizer.php is also
// require'd under Zend for the differential harness, where those constants
// already exist. Class constants cannot collide, so the ids arrive as
// __McTokId::WHITESPACE.
// The T_ prefix is KEPT: `class`, `function`, `list` and friends are reserved
// as bare class-constant names, and in class scope T_CLASS cannot collide with
// the global constant anyway.
$idConsts = '';
foreach ($reverse as $id => $n) {
    $idConsts .= '    public const ' . $n . ' = ' . $id . ";\n";
}

$preludeTables = BEGIN . "\n"
    . "// php {$ver}. Regenerate with: php tools/gen_tokenizer_tables.php\n"
    . "\n"
    . "/** T_* ids as class constants — see the note in the generator. */\n"
    . "final class __McTokId\n{\n"
    . $idConsts
    . "}\n"
    . "\n"
    . "/** T_* id -> name, for token_name(). @return array<int,string> */\n"
    . "function __mc_tok_names(): array\n{\n    return [\n"
    . phpStrMap($reverse, 8)
    . "    ];\n}\n"
    . "\n"
    . "/** lowercase keyword -> T_* id. @return array<string,int> */\n"
    . "function __mc_tok_keywords(): array\n{\n    return [\n"
    . phpIntMap($kw, 8)
    . "    ];\n}\n"
    . "\n"
    . "/** lowercase magic constant -> T_* id. @return array<string,int> */\n"
    . "function __mc_tok_magic(): array\n{\n    return [\n"
    . phpIntMap($magic, 8)
    . "    ];\n}\n"
    . "\n"
    . "/** lowercase cast word (no parens) -> T_* id. @return array<string,int> */\n"
    . "function __mc_tok_casts(): array\n{\n    return [\n"
    . phpIntMap($casts, 8)
    . "    ];\n}\n"
    . "\n"
    . "/** multi-byte operator -> T_* id; single bytes stay bare strings.\n"
    . " *  @return array<string,int> */\n"
    . "function __mc_tok_operators(): array\n{\n    return [\n"
    . phpIntMap($ops, 8)
    . "    ];\n}\n"
    . "\n"
    . "/** php 8.4 asymmetric visibility: ONE token despite the parens. */\n"
    . "function __mc_tok_paren_keywords(): array\n{\n    return [\n"
    . phpIntMap($parenKw, 8)
    . "    ];\n}\n"
    . "\n"
    . "/** `yield from` is ONE token whose text spans the inner whitespace. */\n"
    . "function __mc_tok_yield_from(): int { return {$yieldFrom}; }\n"
    . "\n"
    . "/** `enum` is CONTEXTUAL — this id only when whitespace + an identifier\n"
    . " *  follows; otherwise the keyword table's T_STRING id stands. */\n"
    . "function __mc_tok_enum(): int { return {$enumKeywordId}; }\n"
    . "\n"
    . "/** `&` is decided by LOOKAHEAD past whitespace: a variable or `...` next. */\n"
    . "function __mc_tok_amp_followed(): int { return {$ampFollowed}; }\n"
    . "function __mc_tok_amp_plain(): int { return {$ampPlain}; }\n"
    . "\n"
    . END . "\n";

/** Replace the marked region by literal search — never a regex. */
function spliceGenerated(string $file, string $body): string
{
    $src = file_get_contents($file);
    if ($src === false) { fwrite(STDERR, "cannot read $file\n"); exit(1); }
    $a = strpos($src, BEGIN);
    $b = strpos($src, END);
    if ($a === false || $b === false || $b < $a) {
        fwrite(STDERR, "$file has no GENERATED markers\n");
        exit(1);
    }
    return substr($src, 0, $a) . $body . substr($src, $b + strlen(END) + 1);
}

$newPrelude = file_exists(PRELUDE_FILE) ? spliceGenerated(PRELUDE_FILE, $preludeTables) : null;

if ($check) {
    $bad = 0;
    $have = @file_get_contents(CONSTS_FILE);
    if ($have !== $constsSrc) { echo "STALE: " . CONSTS_FILE . "\n"; $bad++; }
    if ($newPrelude !== null && @file_get_contents(PRELUDE_FILE) !== $newPrelude) {
        echo "STALE: " . PRELUDE_FILE . "\n"; $bad++;
    }
    if ($bad === 0) { echo "tokenizer tables up to date (php {$ver})\n"; }
    exit($bad === 0 ? 0 : 1);
}

file_put_contents(CONSTS_FILE, $constsSrc);
echo "wrote " . CONSTS_FILE . " (" . count($names) . " constants, php {$ver})\n";

if ($newPrelude !== null) {
    file_put_contents(PRELUDE_FILE, $newPrelude);
    echo "wrote " . PRELUDE_FILE . " tables\n";
} else {
    echo "skipped " . PRELUDE_FILE . " (does not exist yet)\n";
}

echo "keywords " . count($kw) . " · magic " . count($magic) . " · casts "
    . count($casts) . " · operators " . count($ops) . "\n";
if ($bare !== []) { echo "bare/split (no id): " . implode(' ', $bare) . "\n"; }
echo "ids produced dynamically by the scanner (" . count($dynamic) . "): "
    . implode(' ', $dynamic) . "\n";
